woowacourse-teams/2022-f12

backend/src/main/java/com/woowacourse/f12/domain/Review.java
backend/src/main/java/com/woowacourse/f12/exception/InvalidRatingValueException.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/ReviewTest.java

- 리뷰 도메인의 별점을 검증한다.
-  별점은 1점 부터 5점 사이여야 한다.

[BE] 리뷰 도메인의 별점을 검증한다.

---

backend/src/main/java/com/woowacourse/f12/F12Application.java
backend/src/main/java/com/woowacourse/f12/config/JpaConfig.java
backend/src/test/java/com/woowacourse/f12/F12ApplicationTests.java
backend/src/test/java/com/woowacourse/f12/domain/ReviewRepositoryTest.java

[BE] 스프링부트의 설정으로부터 Jpa 설정을 분리한다. 

---

backend/src/main/java/com/woowacourse/f12/domain/Keyboard.java
backend/src/main/java/com/woowacourse/f12/dto/response/KeyboardResponse.java
backend/src/test/java/com/woowacourse/f12/acceptance/KeyboardAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/domain/KeyboardRepositoryTest.java

- Keyboard 엔티티에 imageUrl 필드 추가

[BE] 키보드 도메인에 필요한 이미지 url 필드 추가

---

backend/src/main/java/com/woowacourse/f12/domain/Review.java
backend/src/main/java/com/woowacourse/f12/exception/BlankContentException.java
backend/src/main/java/com/woowacourse/f12/exception/InvalidContentLengthException.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/ReviewTest.java

- 리뷰 내용이 1000자를 넘을 수 없도록 제한했다.
- 리뷰 내용이 비어있을 수 없도록 제한했다.

[BE] 리뷰 내용을 검증하는 기능 구현

---

.github/workflows/backend.yml

- `.github/workflows/backend.yml`을 작성
- main 브랜치에 push 또는 pull request 시 GitHub Actions가 실행되어 gradle 빌드를 진행하도록 설정했다.
- backend 디렉토리 아래에 수정 사항이 있을 때만 gradle 빌드를 진행하도록 설정했다.

chore: GitHub Actions 설정

---

.github/workflows/backend.yml

- 스크립트에 `working directory` 추가

[BE] GitHub Actions 스크립트에 working directory 추가

---

.github/workflows/backend.yml

- yml 파일 syntax 오류로 빌드 진행되지 않는 오류 수정

[BE] yml syntax 오류 수정

---

.github/workflows/backend.yml

- `runs`를 써야 하는 부분에 `uses`를 사용하여 에러가 나는 부분을 수정했다.

[BE] CI 스크립트 문법 오류 수정

---

backend/src/main/java/com/woowacourse/f12/domain/Keyboard.java
backend/src/main/java/com/woowacourse/f12/domain/Review.java

[BE] DB 제약조건을 Entity에 추가

---

backend/src/main/java/com/woowacourse/f12/dto/response/ExceptionResponse.java
backend/src/main/java/com/woowacourse/f12/exception/BlankContentException.java
backend/src/main/java/com/woowacourse/f12/exception/InvalidContentLengthException.java
backend/src/main/java/com/woowacourse/f12/exception/InvalidPageSizeException.java
backend/src/main/java/com/woowacourse/f12/exception/InvalidRatingValueException.java
backend/src/main/java/com/woowacourse/f12/exception/InvalidValueException.java
backend/src/main/java/com/woowacourse/f12/exception/KeyboardNotFoundException.java
backend/src/main/java/com/woowacourse/f12/exception/NotFoundException.java
backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java

- NotFoundException 핸들러 구현했다.
- InvalidValueException 핸들러 구현했다.

[BE] API 예외 처리 구현

---

backend/src/main/java/com/woowacourse/f12/config/WebConfig.java
backend/src/main/java/com/woowacourse/f12/presentation/CustomPageableHandlerMethodArgumentResolver.java

- CustomPageableHandlerArgumentResolver를 CustomPageableHandlerMethodArgumentResolver 로 변경했다.
- CustomPageableHandlerMethodArgumentResolver resolveArgument 메서드 로컬 변수에 final 키워드를 추가했다.

[BE] CustomPageableHandlerArgumentResolver 이름 변경

---

backend/src/main/java/com/woowacourse/f12/domain/Review.java
backend/src/main/java/com/woowacourse/f12/dto/response/KeyboardPageResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/ReviewPageResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/ReviewResponse.java
backend/src/test/java/com/woowacourse/f12/acceptance/KeyboardAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/KeyboardServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java

- ReviewResponse에 createdAt 필드 추가
- KeyboardPageResponse, ReviewPageResponse의 list 필드명 items로 변경
- 리뷰 생성자에 createdAt 파라미터 추가

[BE] DTO의 필드 정보 변경

---

backend/src/test/java/com/woowacourse/f12/presentation/KeyboardControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/ReviewControllerTest.java

- KeyboardController와 ReviewController를 WebMvcTest를 통해 슬라이스 테스트 했다.

[BE] Controller를 테스트

---

frontend/src/constants/api.ts
frontend/src/hooks/useProducts.tsx
frontend/src/pages/Home/Home.tsx
frontend/webpack.config.js

- API base url 수정
- 정렬 관련 오류 수정

[FE] API base url 수정, 정렬 관련 오류 수정

---

backend/src/main/java/com/woowacourse/f12/application/ReviewService.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/ReviewControllerTest.java

- 리뷰를 등록할 때 해당 제품이 존재하지 않으면 예외가 발생하도록 수정했다.
- 특정 상품에 대한 리뷰를 조회할 때 상품이 존재하지 않으면 예외가 발생하도록 수정했다.

[BE] 상품에 대한 리뷰를 저장 및 조회할 때 상품이 존재하는지 확인

---

backend/src/test/java/com/woowacourse/f12/acceptance/KeyboardAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/KeyboardServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/KeyboardRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/ReviewRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/KeyboardControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/ReviewControllerTest.java
backend/src/test/java/com/woowacourse/f12/support/KeyboardFixtures.java
backend/src/test/java/com/woowacourse/f12/support/ReviewFixtures.java

- Keyboard, Review Fixtures를 생성했다.
- 테스트 반복 코드를 제거했다.

[BE] 테스트 반복 코드 제거

---

frontend/src/components/ProductListSection/ProductListSection.style.tsx
frontend/src/components/ProductListSection/ProductListSection.tsx
frontend/src/components/ReviewListSection/ReviewListSection.style.tsx
frontend/src/components/common/Masonry/Masonry.style.tsx
frontend/src/components/common/Masonry/Masonry.tsx
frontend/src/components/common/ProductCard/ProductCard.style.tsx
frontend/src/components/common/ProductCard/ProductCard.tsx
frontend/src/components/common/ProductDetail/ProductDetail.style.tsx
frontend/src/components/common/ReviewCard/ReviewCard.style.tsx
frontend/src/components/common/ReviewForm/ReviewForm.style.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Home/Home.tsx
frontend/src/pages/Product/Product.style.tsx

- Masonry 구현 및 반영
- 기타 목록 스타일 일부 수정

[FE] Masonry 구현 및 반영, 기타 목록 스타일 일부 수정

---

frontend/src/components/ReviewListSection/ReviewListSection.style.tsx
frontend/src/components/ReviewListSection/ReviewListSection.tsx
frontend/src/components/common/Masonry/Masonry.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Home/Home.tsx
frontend/src/pages/Product/Product.tsx

- Masonry 컴포넌트 리팩토링
- 리뷰 목록 페이지 수정

[FE] Masonry 컴포넌트 리팩토링 및 리뷰 목록 페이지 수정

---

frontend/src/constants/api.ts

[FE] API URL 수정

---

backend/build.gradle
backend/src/docs/asciidoc/keyboards.adoc
backend/src/docs/asciidoc/reviews.adoc
backend/src/test/java/com/woowacourse/f12/documentation/Documentation.java
backend/src/test/java/com/woowacourse/f12/documentation/KeyboardDocumentation.java
backend/src/test/java/com/woowacourse/f12/documentation/RestDocsConfig.java
backend/src/test/java/com/woowacourse/f12/documentation/ReviewDocumentation.java

[BE] Spring REST Docs 적용

---

backend/src/main/resources/application.yml

- `application.yml`의 데이터베이스 주소를 테스트 환경 데이터베이스로 변경

[BugFix] 테스트 환경 데이터베이스에 연결하도록 수정

---

frontend/src/components/ReviewListSection/ReviewListSection.tsx
frontend/src/components/common/ReviewCard/ReviewCard.style.tsx
frontend/src/components/common/ReviewCard/ReviewCard.tsx
frontend/src/custom.d.ts
frontend/src/mocks/data.ts
frontend/src/pages/Home/Home.tsx

- 리뷰카드에 상품 정보(상품 이미지, 상품 제목)를 표기

[FE] 리뷰카드에 상품 정보 표기 구현

---

frontend/src/components/common/Stepper/Stepper.stories.tsx
frontend/src/components/common/Stepper/Stepper.style.ts
frontend/src/components/common/Stepper/Stepper.tsx
frontend/src/constants/routes.ts
frontend/src/pages/Register/Register.style.tsx
frontend/src/pages/Register/Register.tsx
frontend/src/pages/index.tsx

- Stepper 컴포넌트 구현
- 추가 정보 입력 페이지 구현
- Stepper 스토리북 작성

[FE] 추가 정보 입력 페이지 구현

---

frontend/src/components/ProductListSection/ProductListSection.style.tsx
frontend/src/components/ProductListSection/ProductListSection.tsx
frontend/src/components/ReviewListSection/ReviewListSection.stories.tsx
frontend/src/components/ReviewListSection/ReviewListSection.style.tsx
frontend/src/components/common/Masonry/Masonry.style.tsx
frontend/src/components/common/ProductCard/ProductCard.style.tsx
frontend/src/components/common/ProductCard/ProductCard.tsx
frontend/src/components/common/ProductDetail/ProductDetail.style.tsx
frontend/src/components/common/Rating/Rating.tsx
frontend/src/components/common/ReviewCard/ReviewCard.stories.tsx
frontend/src/components/common/ReviewCard/ReviewCard.style.tsx
frontend/src/components/common/ReviewCard/ReviewCard.tsx
frontend/src/components/common/SectionHeader/SectionHeader.style.tsx
frontend/src/custom.d.ts
frontend/src/mocks/data.ts
frontend/src/mocks/handlers.ts
frontend/src/pages/Home/Home.tsx
frontend/src/pages/Products/Products.tsx
frontend/src/pages/common/PageLayout/PageLayout.style.tsx

- 상품 카드 수정
- 리뷰 카드 수정
- 정수인 평점 컴포넌트 형태 변경 (하트 + 평점 => n개 하트 나열)
- 상품 목록을 5열 => 4열로 변경
- 상품 목록과 리뷰 목록이 화면 전체를 차지하도록 수정

[FE] 상품 카드, 리뷰 카드 스타일 수정 및 목록 레이아웃 스타일 수정

---

frontend/src/components/ReviewBottomSheet/ReviewBottomSheet.style.tsx
frontend/src/components/ReviewBottomSheet/ReviewBottomSheet.tsx
frontend/src/components/common/BottomSheet/BottomSheet.style.tsx
frontend/src/components/common/BottomSheet/BottomSheet.tsx
frontend/src/components/common/FloatingButton/FloatingButton.stories.tsx
frontend/src/components/common/FloatingButton/FloatingButton.style.tsx
frontend/src/components/common/FloatingButton/FloatingButton.tsx
frontend/src/components/common/FloatingButton/plus.svg
frontend/src/hooks/api/useGetMany.tsx
frontend/src/hooks/useReviews.tsx
frontend/src/pages/Product/Product.tsx
frontend/src/style/GlobalStyles.tsx

리뷰 작성 UI,UX 개선 진행
- 아직 평점은 바로 반영되지 않음
- 오류 처리 관련 로직은 아직 미구현
- useReviews, useGetOne 훅에 수정 있으므로 주의 필요

[FE] 리뷰 작성 및 제출 시 UI 및 작동 로직 수정

---

frontend/src/components/common/ReviewForm/ReviewForm.tsx

빈 칸 입력으로 제출 불가하도록 검증 강화
- trim() 매서드를 사용해서 빈 칸을 제거
- 검증 매서드를 직접 상태를 참고하는 방식에서 인자를 받아서 처리하는 방식으로 수정

[FE] 리뷰 입력란 검증 강화 (빈 칸)

---

frontend/src/components/common/ReviewForm/ReviewForm.style.tsx
frontend/src/components/common/ReviewForm/ReviewForm.tsx

입력란 유효성 검증 오류 시 UI 추가
- 전체 폼에 대한 오류 메시지 추가
- 각 항목에서 빈 칸인 경우 오류 메시지 추가
- 입력 값 변경 시 오류 메시지 초기화

[FE] 입력란 유효성 검증 오류 시 UI 추가

---

backend/src/main/java/com/woowacourse/f12/application/GitHubOauthClient.java
backend/src/main/java/com/woowacourse/f12/exception/UnAuthorizedException.java
backend/src/main/java/com/woowacourse/f12/exception/UnauthorizedException.java
backend/src/main/java/com/woowacourse/f12/presentation/AuthArgumentResolver.java
backend/src/main/java/com/woowacourse/f12/presentation/AuthInterceptor.java
backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
backend/src/main/java/com/woowacourse/f12/support/AuthTokenExtractor.java
backend/src/test/java/com/woowacourse/f12/support/AuthTokenExtractorTest.java

- `UnAuthorizedException` -> `UnauthorizedException`
- `GitHubOauthClient`에서 HTTP 통신하는 부분 메서드 분리
- `AuthInterceptor`의 `preHandle` 메서드 리팩토링

[BE] 코드 리뷰 사항 반영

---

frontend/src/components/common/ReviewCard/ReviewCard.style.tsx

github conflict resolve 시에 지우지 않아서 오류 발생한 부분 수정

fix: conflict resolve 시 발생한 스타일 오류 수정

---

frontend/src/constants/api.ts

- github auth url에서 redirect_uri query param 제거

[Bugfix] github auth url 수정

---

README.md

[BE] PR시 빌드를 실행하는 지 확인

---

frontend/src/components/Login/Login.tsx

- 로그인 시 code 접근 훅을 params에서 searchParam으로 수정

[BugFix] 로그인 시 code 접근 못하는 버그 수정

---

frontend/src/contexts/LoginContextProvider.tsx
frontend/src/custom.d.ts
frontend/src/mocks/handlers.ts

[BugFix] FE 토큰 변수명 수정

---

frontend/src/components/ReviewListSection/ReviewListSection.tsx
frontend/src/components/common/ReviewCard/ReviewCard.style.tsx
frontend/src/components/common/ReviewCard/ReviewCard.tsx
frontend/src/constants/api.ts
frontend/src/contexts/LoginContextProvider.tsx
frontend/src/custom.d.ts
frontend/src/hooks/api/useDelete.tsx
frontend/src/hooks/useReviews.tsx
frontend/src/mocks/data.ts
frontend/src/mocks/handlers.ts
frontend/src/pages/Product/Product.tsx

- 리뷰 삭제 기능 구현
- 자신이 작성한 리뷰만 삭제 가능

[FE] 리뷰를 삭제하는 기능을 구현

---

frontend/src/hooks/useReviews.tsx

- 리뷰를 작성할 때 로그인한 사용자의 정보를 함께 보낸다.

[FE] 리뷰를 작성하는 기능을 보완

---

backend/src/docs/asciidoc/reviews.adoc
backend/src/main/java/com/woowacourse/f12/application/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/Review.java
backend/src/main/java/com/woowacourse/f12/presentation/ReviewController.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/support/RestAssuredRequestUtil.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/ReviewDocumentation.java
backend/src/test/java/com/woowacourse/f12/domain/ReviewTest.java
backend/src/test/java/com/woowacourse/f12/presentation/ReviewControllerTest.java

- 리뷰 수정 기능 구현
- 리뷰 수정은 JPA의 변경 감지 방식을 사용

[BE] 리뷰 수정 기능 구현

---

backend/src/main/java/com/woowacourse/f12/application/InventoryProductService.java
backend/src/main/java/com/woowacourse/f12/exception/InvalidProfileProductException.java
backend/src/test/java/com/woowacourse/f12/application/InventoryProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/InventoryProductControllerTest.java

- 대표 장비를 업데이트할 때 요청된 장비가 모두 null인 경우 예외가 발생하도록 수정

[BE] 대표 장비를 업데이트할 때 요청된 장비를 검증

---

frontend/src/assets/down_arrow.svg
frontend/src/components/common/Chip/Chip.stories.tsx
frontend/src/components/common/Chip/Chip.style.tsx
frontend/src/components/common/Chip/Chip.tsx
frontend/src/components/common/HeaderNav/HeaderNav.style.tsx
frontend/src/components/common/HeaderNav/HeaderNav.tsx
frontend/src/components/common/ProductBar/ProductBar.stories.tsx
frontend/src/components/common/ProductBar/ProductBar.style.tsx
frontend/src/components/common/ProductBar/ProductBar.tsx
frontend/src/components/common/ProductSelect/ProductSelect.stories.tsx
frontend/src/components/common/ProductSelect/ProductSelect.style.tsx
frontend/src/components/common/ProductSelect/ProductSelect.tsx
frontend/src/components/common/UserInfo/UserInfo.stories.tsx
frontend/src/components/common/UserInfo/UserInfo.styled.tsx
frontend/src/components/common/UserInfo/UserInfo.tsx
frontend/src/constants/api.ts
frontend/src/constants/routes.ts
frontend/src/contexts/LoginContextProvider.tsx
frontend/src/custom.d.ts
frontend/src/hooks/api/useGetOne.tsx
frontend/src/hooks/api/usePatch.tsx
frontend/src/hooks/useInventory.tsx
frontend/src/hooks/useProduct.tsx
frontend/src/mocks/data.ts
frontend/src/mocks/handlers.ts
frontend/src/pages/Profile/Profile.style.tsx
frontend/src/pages/Profile/Profile.tsx
frontend/src/pages/index.tsx

- 프로필 페이지 UI 구현
- API 모킹 구현
- API 연결 로직 구현

[FE] 프로필 페이지 UI 구현, API 모킹 구현, API 연결 로직 구현

---

frontend/src/components/ReviewBottomSheet/ReviewBottomSheet.tsx
frontend/src/components/ReviewListSection/ReviewListSection.tsx
frontend/src/components/common/ReviewCard/ReviewCard.tsx
frontend/src/components/common/ReviewForm/ReviewForm.tsx
frontend/src/constants/api.ts
frontend/src/hooks/api/usePut.tsx
frontend/src/hooks/useReviews.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Product/Product.tsx

- 리뷰를 수정하는 기능을 구현한다.
- 수정 버튼 클릭 시 이전 rating, content를 보여준다.

[FE] 리뷰를 수정하는 기능을 구현

---

backend/src/docs/asciidoc/inventoryProducts.adoc
backend/src/main/java/com/woowacourse/f12/application/InventoryProductService.java
backend/src/main/java/com/woowacourse/f12/domain/InventoryProduct.java
backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/InventoryProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/InventoryDocumentation.java
backend/src/test/java/com/woowacourse/f12/presentation/InventoryProductControllerTest.java

- 코드 포맷팅, 변수명 변경
- 메서드 분리
- 회원이 있는지 확인할 때 findById 대신에 existById를 사용하도록 변경

[BE] 인벤토리 기능 구현에 대한 피드백 반영

---

frontend/src/hooks/useInventory.tsx

- 기존: 인벤토리 목록의 경우에도 조회 시에는 토큰을 보내지 않아서 서버에서 접근이 안되는 오류가 있었음
- 수정: 토큰을 보내도록 수정

[BugFix] 인벤토리 목록의 경우 조회 시에도 토큰을 보내도록 수정

---

frontend/src/hooks/useInventory.tsx

- 오류: 대표 장비 수정을 여러 번 하면 제대로 수정되지 않는 오류
- 원인: useRef를 이용해 초기 선택 값을 지정했는데, 새로고침 시에는 이것이 업데이트 되지 않아서 unselect할 상품이 제대로 지정되지 않음
- 수정: useMemo로 변경해서 새로고침을 하면 기본 선택 값 또한 업데이트 되도록 수정

[BugFix] 대표 장비 수정을 여러 번 하면 제대로 수정되지 않는 오류 수정

---

frontend/src/components/ReviewListSection/ReviewListSection.tsx
frontend/src/components/common/ReviewCard/ReviewCard.tsx
frontend/src/constants/api.ts
frontend/src/custom.d.ts
frontend/src/hooks/api/useDelete.tsx
frontend/src/hooks/api/usePost.tsx
frontend/src/hooks/api/usePut.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Product/Product.tsx

[FE] 리뷰 CRUD의 피드백을 반영

---

frontend/src/components/common/ProductSelect/ProductSelect.style.tsx
frontend/src/components/common/ProductSelect/ProductSelect.tsx
frontend/src/constants/api.ts
frontend/src/contexts/InventoryContextProvider.tsx
frontend/src/contexts/LoginContextProvider.tsx
frontend/src/hooks/useInventory.tsx
frontend/src/mocks/data.ts
frontend/src/mocks/handlers.ts
frontend/src/pages/Profile/Profile.tsx
frontend/src/pages/index.tsx

- 프로필 페이지 UI 개선
- 사용자 정보를 직접 받아와서 표시하도록 API 연결
- 상품 선택 컴포넌트 스타일 개선
- 인벤토리 API 개선
- 요청을 두 번 보내던 버그 수정
- 프로필 페이지에서 로그아웃 시 오류 수정

[FE] 프로필 페이지 UI 및 API 요청 개선

---

frontend/src/constants/api.ts
frontend/src/hooks/useReviews.tsx
frontend/src/mocks/handlers.ts

- API 명세 불일치 수정
- msw api mocking 수정

[BugFix] 리뷰 UD 오류 수정

---

backend/src/main/java/com/woowacourse/f12/application/ReviewService.java
backend/src/main/java/com/woowacourse/f12/presentation/ReviewController.java
backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/ReviewDocumentation.java
backend/src/test/java/com/woowacourse/f12/presentation/AuthInterceptorTest.java
backend/src/test/java/com/woowacourse/f12/presentation/ReviewControllerTest.java

- 리뷰를 작성하면 해당하는 장비가 인벤토리에 추가되도록 하는 기능 추가
- 리뷰 작성과 인벤토리 추가가 같은 트랜잭션 내에서 진행되어 하나라도 실패하면 모두 롤백

[BE] 리뷰를 작성하면 해당하는 장비가 인벤토리에 추가되도록 하는 기능 추가

---

frontend/src/components/common/ProductSelect/ProductSelect.style.tsx
frontend/src/components/common/ProductSelect/ProductSelect.tsx
frontend/src/constants/api.ts
frontend/src/contexts/InventoryContextProvider.tsx
frontend/src/contexts/LoginContextProvider.tsx
frontend/src/hooks/useInventory.tsx
frontend/src/mocks/data.ts
frontend/src/mocks/handlers.ts
frontend/src/pages/Profile/Profile.tsx
frontend/src/pages/index.tsx

- 인벤토리 목록을 불러오는 요청의 결과를 컨텍스트에 저장하게 수정
- product select 컴포넌트 스타일 수정
- 프로필 페이지에서 로그아웃 시 홈 페이지로 이동 구현
- 사용자 정보를 프로필에 반영하도록 구현

[Release] 프로필 페이지 UI 및 API 요청 개선

---

backend/src/docs/asciidoc/inventoryProducts.adoc
backend/src/docs/asciidoc/members.adoc
backend/src/main/java/com/woowacourse/f12/domain/CareerLevel.java
backend/src/main/java/com/woowacourse/f12/domain/JobType.java
backend/src/main/java/com/woowacourse/f12/domain/Member.java
backend/src/main/java/com/woowacourse/f12/dto/response/LoginMemberResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/MemberController.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/InventoryProductDocumentation.java
backend/src/test/java/com/woowacourse/f12/documentation/MemberDocumentation.java

[BE] 회원 관련 기능 피드백 반영한다.

---

frontend/src/components/common/HeaderNav/HeaderNav.style.tsx
frontend/src/components/common/HeaderNav/HeaderNav.tsx
frontend/src/constants/api.ts
frontend/src/constants/routes.ts
frontend/src/contexts/LoginContextProvider.tsx
frontend/src/custom.d.ts
frontend/src/mocks/handlers.ts
frontend/src/pages/index.tsx

[FE] 롤백된 파일 변경 내용을 복원

---

frontend/src/components/common/HeaderNav/HeaderNav.tsx
frontend/src/pages/Products/Products.tsx

- 전체 상품 목록, 인기 상품 목록 Link 추가
- React-router-dom Link의 hash 속성을 활용하여 hash value의 유무에 따라 정렬 조건을 변경
- 타입에서 제거
- options 배열에서 제거

[FE] 스프린트 2 데모를 위한 UI 마무리

---

backend/src/main/java/com/woowacourse/f12/domain/InventoryProduct.java
backend/src/test/java/com/woowacourse/f12/acceptance/AcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/support/DatabaseCleanup.java
backend/src/test/java/com/woowacourse/f12/application/InventoryProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/InventoryProductDocumentation.java
backend/src/test/java/com/woowacourse/f12/domain/InventoryProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/InventoryProductControllerTest.java
backend/src/test/java/com/woowacourse/f12/support/InventoryProductFixtures.java

- InventoryProductFixture를 구현했다.
- DirtiesContext를 제거하고 EntityManager로 테이블을 truncate 시켰다.
- 대표장비 등록API의 등록 된 결과를 확인하도록 수정

[BE] 테스트를 리팩토링

---

backend/src/docs/asciidoc/reviews.adoc
backend/src/main/java/com/woowacourse/f12/application/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/ReviewRepository.java
backend/src/main/java/com/woowacourse/f12/exception/AlreadyWrittenReviewException.java
backend/src/test/java/com/woowacourse/f12/acceptance/AuthAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/KeyboardAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/support/LoginUtil.java
backend/src/test/java/com/woowacourse/f12/application/GitHubOauthClientTest.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/ReviewDocumentation.java
backend/src/test/java/com/woowacourse/f12/domain/ReviewRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/ReviewControllerTest.java
backend/src/test/java/com/woowacourse/f12/support/FakeGitHubApiController.java
backend/src/test/java/com/woowacourse/f12/support/MemberFixtures.java

- 동일한 장비에 대해 리뷰를 중복 작성하지 못하도록 구현
- login fixture 생성
- 같은 회원이 동일한 제품에 리뷰를 남길경우 예외 발생하는 API 문서화

[BE] 동일한 장비에 대해 리뷰를 중복 작성하지 못하도록 구현

---

.gitmodules
backend/build.gradle

- `application-auth.yml` 파일을 서브모듈을 통해 가져오도록 설정

[BE] auth 설정 파일 서브모듈 적용

---

frontend/src/custom.d.ts
frontend/src/mocks/data.ts

- 리뷰 카드에서 사용자 아이디가 보이지 않는 문제를 수정
- 모킹 데이터에서 발생하는 타입스크립트 에러를 수정

[FE] 모킹 데이터에서 발생하는 에러를 수정

---

.gitmodules
backend/build.gradle

[Feature, BE] auth 설정 파일 서브모듈 적용 

---

test.md

Reverts woowacourse-teams/2022-f12#248

Revert "Update test.md"

---

frontend/src/components/Login/Login.tsx
frontend/src/contexts/LoginContextProvider.tsx
frontend/src/custom.d.ts
frontend/src/hooks/useAuth.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/common/NonUserRoutes/NonUserRoutes.tsx
frontend/src/pages/common/ProtectedRoute/ProtectedRoutes.tsx
frontend/src/pages/common/UserRoutes/UserRoutes.tsx
frontend/src/pages/index.tsx

- Protected Routes라는 이름으로 회원/비회원 라우팅 분기 처리하는 컴포넌트 구현
- 실제 루트들에 적용
- 로그인 후 추가정보 입력이 되지 않았으면 입력창으로 넘어가고 아니면 홈으로 넘어가는 라우팅 구현

[FE] Private Route 컴포넌트 구현 및 적용

---

frontend/src/components/common/CategoryNav/CategoryNav.style.tsx
frontend/src/components/common/CategoryNav/CategoryNav.tsx
frontend/src/components/common/HeaderNav/HeaderNav.style.tsx
frontend/src/components/common/HeaderNav/HeaderNav.tsx
frontend/src/hooks/useAnimation.tsx
frontend/src/style/ResetCss.tsx

- 상단 메뉴바 바로 아래에 메뉴 추가
- 애니메이션 훅 추가
- 마운트/언마운트 시 애니메이션 적용

[FE] 카테고리 상단 메뉴 구현

---

frontend/src/components/SearchFilter/SearchFilter.stories.tsx
frontend/src/components/SearchFilter/SearchFilter.style.tsx
frontend/src/components/SearchFilter/SearchFilter.tsx
frontend/src/components/common/ChipFilter/ChipFilter.stories.tsx
frontend/src/components/common/ChipFilter/ChipFilter.style.tsx
frontend/src/components/common/ChipFilter/ChipFilter.tsx

- 기존 Chip은 div이기 때문에 재사용이 불가능하여 FilterChip을 버튼으로 별도 구현
- SearchFilter 컴포넌트 구현

[FE] 검색 필터 컴포넌트 구현 

---

backend/src/main/resources/application.yml

- `application.yml`에 있는 h2 관련된 설정을 서브모듈에 프로필로 분리 후 적용

[BE] h2 설정 파일 서브모듈 적용

---

backend/.gitignore
backend/src/main/resources/application.yml

- h2 설정 파일 서브모듈 적용
- h2 데이터베이스 접속 비밀번호 설정
- 서브모듈로 분리한 h2 설정 파일 ignore

[Feature/BE] h2 데이터베이스에 관련된 설정을 서브모듈로 분리

---

backend/src/docs/asciidoc/products.adoc
backend/src/main/java/com/woowacourse/f12/application/product/ProductService.java
backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProduct.java
backend/src/main/java/com/woowacourse/f12/domain/product/Category.java
backend/src/main/java/com/woowacourse/f12/dto/response/product/ProductResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
backend/src/main/java/com/woowacourse/f12/presentation/product/CategoryConstant.java
backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/product/ProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/product/ProductDocumentation.java
backend/src/test/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolverTest.java
backend/src/test/java/com/woowacourse/f12/presentation/product/CategoryConstantTest.java
backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java

[BE] 제품 카테고리 속성 추가 피드백 반영

---

backend/build.gradle
backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/CareerLevel.java
backend/src/main/java/com/woowacourse/f12/domain/member/JobType.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustom.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/dto/CareerLevelConstant.java
backend/src/main/java/com/woowacourse/f12/dto/JobTypeConstant.java
backend/src/main/java/com/woowacourse/f12/dto/response/auth/LoginMemberResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberPageResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberWithProfileProductResponse.java
backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/member/MemberDocumentation.java
backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java
backend/src/test/java/com/woowacourse/f12/support/MemberFixtures.java

- querydsl gradle 설정 변경
- Presentation Enum name 변경 (CareerLevelConstant, JobTypeConstant)

[BE] 회원 검색 기능 피드백 반영

---

frontend/src/components/Login/Login.tsx
frontend/src/components/common/CategoryNav/CategoryNav.style.tsx
frontend/src/components/common/CategoryNav/CategoryNav.tsx
frontend/src/components/common/HeaderNav/HeaderNav.style.tsx
frontend/src/components/common/HeaderNav/HeaderNav.tsx
frontend/src/constants/api.ts
frontend/src/contexts/LoginContextProvider.tsx
frontend/src/custom.d.ts
frontend/src/hooks/api/useGetMany.tsx
frontend/src/hooks/useAnimation.tsx
frontend/src/hooks/useAuth.tsx
frontend/src/hooks/useProducts.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Home/Home.tsx
frontend/src/pages/Products/Products.tsx
frontend/src/pages/common/NonUserRoutes/NonUserRoutes.tsx
frontend/src/pages/common/ProtectedRoute/ProtectedRoutes.tsx
frontend/src/pages/common/UserRoutes/UserRoutes.tsx
frontend/src/pages/index.tsx
frontend/src/style/ResetCss.tsx

- Private Route 구현
- 카테고리 상단 메뉴바 구현
- 카테고리 페이지 구현
- Release와 conflict 해결

[Feature/FE] Private Route 처리 및 카테고리 페이지 구현

---

backend/src/test/java/com/woowacourse/f12/acceptance/AuthAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/GitHubOauthClientTest.java
backend/src/test/java/com/woowacourse/f12/support/FakeGitHubApiController.java
backend/src/test/java/com/woowacourse/f12/support/GitHubProfileFixtures.java

-  GitHubProfileFixtures 생성 및 FakeGitHubApiController 리팩토링

[BE] fake github api를 리팩토링

---

backend/build.gradle

- Spring REST Docs gradle 설정 변경

[BugFix] Spring REST Docs가 생기지 않는 버그 수정완료

---

frontend/src/components/BarGraph/BarGraph.stories.tsx
frontend/src/components/BarGraph/BarGraph.style.tsx
frontend/src/components/BarGraph/BarGraph.tsx

[FE] 유저 통계 컴포넌트 구현

---

frontend/src/components/ProductListSection/ProductListSection.style.tsx
frontend/src/components/ProductListSection/ProductListSection.tsx
frontend/src/components/ReviewListSection/ReviewListSection.style.tsx
frontend/src/components/ReviewListSection/ReviewListSection.tsx
frontend/src/components/common/AsyncWrapper/AsyncWrapper.tsx
frontend/src/components/common/Loading/Loading.tsx
frontend/src/components/common/ProductDetail/ProductDetail.style.tsx
frontend/src/pages/Product/Product.style.tsx
frontend/src/pages/Product/Product.tsx

- 로딩 시 레이아웃 시프트 최소화
- 로딩 이미지 중앙 정렬
- 무한 스크롤 컴포넌트의 오류 이미지 표시 로직 개선

[FE] Loading 및 Error UI 스타일 수정

---

frontend/src/components/common/Modal/Modal.stories.tsx
frontend/src/components/common/Modal/Modal.style.tsx
frontend/src/components/common/Modal/Modal.tsx

[FE] 모달 UI 구현

---

frontend/src/components/common/BarGraph/BarGraph.stories.tsx
frontend/src/components/common/BarGraph/BarGraph.style.tsx
frontend/src/components/common/BarGraph/BarGraph.tsx
frontend/src/custom.d.ts
frontend/src/hooks/useStatistics.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Product/Product.style.tsx
frontend/src/pages/Product/Product.tsx

- 사용자 통계를 연차별, 직군별로 출력하는 기능 구현
- Math.random()으로 토글 시 애니메이션 적용
- 반복되는 코드는 리팩토링 기간에 축약 예정

[FE] 사용자 통계 기능 구현

---

backend/src/main/java/com/woowacourse/f12/application/product/ProductService.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/domain/review/CareerLevelCount.java
backend/src/main/java/com/woowacourse/f12/domain/review/Countable.java
backend/src/main/java/com/woowacourse/f12/domain/review/JobTypeCount.java
backend/src/main/java/com/woowacourse/f12/domain/review/ReviewRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthController.java
backend/src/main/java/com/woowacourse/f12/presentation/product/ProductController.java

- ok 반환일 때 body값 생성하는 방식 통일화
- Q-class static import
- Enum raw type 이용하지 않고, 인터페이스인 MemberInfo 활용

[BE] 사용자 통계 기능 피드백을 반영

---

frontend/src/components/common/BarGraph/BarGraph.stories.tsx
frontend/src/components/common/BarGraph/BarGraph.style.tsx
frontend/src/components/common/BarGraph/BarGraph.tsx
frontend/src/custom.d.ts
frontend/src/hooks/useStatistics.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Product/Product.style.tsx
frontend/src/pages/Product/Product.tsx

- 사용자 통계를 연차별, 직군별로 출력하는 기능 구현
- Math.random()으로 토글 시 애니메이션 적용
- 반복되는 코드는 리팩토링 기간에 축약 예정

[Feature/FE] 사용자 통계 기능 구현

---

frontend/src/components/ProfileCard/ProfileCard.style.tsx
frontend/src/components/ProfileCard/ProfileCard.tsx
frontend/src/components/ProfileSearchResult/ProfileSearchResult.style.tsx
frontend/src/components/ProfileSearchResult/ProfileSearchResult.tsx
frontend/src/components/SearchFilter/SearchFilter.style.tsx
frontend/src/components/SearchFilter/SearchFilter.tsx
frontend/src/components/common/ChipFilter/ChipFilter.style.tsx
frontend/src/components/common/ChipFilter/ChipFilter.tsx
frontend/src/components/common/HeaderNav/HeaderNav.tsx
frontend/src/components/common/SearchBar/SearchBar.style.tsx
frontend/src/components/common/SearchBar/SearchBar.tsx
frontend/src/constants/api.ts
frontend/src/constants/routes.ts
frontend/src/custom.d.ts
frontend/src/hooks/useProfileSearch.tsx
frontend/src/pages/ProfileSearch/ProfileSearch.style.tsx
frontend/src/pages/ProfileSearch/ProfileSearch.tsx
frontend/src/pages/Register/Register.tsx
frontend/src/pages/index.tsx

- 사용자 검색 기능 구현
- 경력, 직무, 쿼리에 따라 다른 검색결과를 출력

[Feature/FE] 사용자 검색 기능 구현

---

.github/workflows/backend.yml

- backend workflow 파일 내부 경로 설정 통일

[BE] backend workflow 파일 내부 경로 설정 통일

---

.github/workflows/backend.yml

- `EnricoMi/publish-unit-test-result-action@v2`로 테스트 리포트 추가
- `mikepenz/action-junit-report@v3`로 PR에 테스트 실패에 대한 comment를 남기도록 설정

[Feature/BE] GitHub Actions workflow에 테스트 리포트 추가

---

.github/workflows/backend.yml

[Bugfix/BE] 테스트 리포트 파일 경로 수정

---

backend/.gitignore
backend/build.gradle
backend/src/main/resources/application.yml

- 서브모듈 적용 방식을 프로필 include에서 파일 import로 변경

[BE] 서브모듈 적용 방식을 프로필 include에서 import로 변경

---

backend/.gitignore
backend/build.gradle
backend/src/main/resources/application.yml

- 서브모듈 적용 방식을 프로필 include에서 import로 변경

[Feature/BE] 서브모듈 적용 방식을 프로필 include에서 import로 변경

---

backend/build.gradle
backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
backend/src/main/java/com/woowacourse/f12/presentation/LogInterceptor.java
backend/src/main/resources/application-local.yml
backend/src/main/resources/application-main.yml
backend/src/main/resources/application-release.yml
backend/src/main/resources/application.yml
backend/src/main/resources/log4j2/log4j2-local.xml
backend/src/main/resources/log4j2/log4j2-main.xml
backend/src/main/resources/log4j2/log4j2-release.xml
backend/src/test/resources/application.yml

- log4j2로 로깅 구현
- 프로파일 별 로깅 전략에 따라 로깅 구현
- 인터셉터로 API 로깅 구현

[BE] 로깅 구현

---

backend/src/main/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductService.java
backend/src/main/java/com/woowacourse/f12/exception/badrequest/DuplicatedProfileProductCategoryException.java
backend/src/main/java/com/woowacourse/f12/exception/badrequest/InvalidProfileProductCategoryException.java
backend/src/test/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductControllerTest.java

- 같은 카테고리에 대해서는 대표장비를 1개만 등록할 수 있는 기능 피드백 반영

[BE] 같은 카테고리에 대해서는 대표장비를 1개만 등록할 수 있는 기능 피드백 반영

---

backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberWithProfileProductResponse.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberTest.java

[BE] 회원 검색 시 대표장비만 조회되도록 수정 코드 리뷰 피드백 반영

---

frontend/src/components/common/BarGraph/BarGraph.style.tsx
frontend/src/components/common/BarGraph/BarGraph.tsx

[FE] 통계 그래프 토글 버튼 수정 요청을 반영

---

backend/.gitignore
backend/src/main/resources/application-local.yml
backend/src/main/resources/application-main.yml
backend/src/main/resources/application-release.yml
backend/src/main/resources/application.yml

- main, release, local 환경에 따라 다른 github oauth app과 데이터베이스에 연결하도록 설정

[BE] main, release, local 환경에 따라 다른 github oauth app과 데이터베이스에 연결하도록 설정

---

backend/build.gradle

[BE] mysql 드라이버 설정

---

backend/build.gradle

[Bugfix/BE] mysql 드라이버 설정

---

frontend/src/components/ProfileCard/ProfileCard.style.tsx
frontend/src/components/ProfileCard/ProfileCard.tsx
frontend/src/components/common/ChipFilter/ChipFilter.style.tsx
frontend/src/custom.d.ts
frontend/src/pages/ProfileSearch/ProfileSearch.tsx

- 현재는 키보드만 등록가능한 상태이기 때문에 마우스, 모니터, 거치대 대표 장비는 존재하지 않는다.
- 키보드, 마우스, 모니터, 거치대를 각각 다른 데이터로 보여주도록 수정한다.
- Chip 선택 항목을 수정한다.
- 토글기능
- 프로필 보기 클릭 시 사용자의 프로필 페이지로 이동한다.

[FE] 프로필 검색 기능 보완

---

frontend/src/components/ProfileCard/ProfileCard.style.tsx
frontend/src/components/ProfileCard/ProfileCard.tsx
frontend/src/components/common/ChipFilter/ChipFilter.style.tsx
frontend/src/custom.d.ts
frontend/src/pages/ProfileSearch/ProfileSearch.tsx

- 현재는 키보드만 등록가능한 상태이기 때문에 마우스, 모니터, 거치대 대표 장비는 존재하지 않는다.
- 키보드, 마우스, 모니터, 거치대를 각각 다른 데이터로 보여주도록 수정한다.
- Chip 선택 항목을 수정한다.
- 토글기능
- 프로필 보기 클릭 시 사용자의 프로필 페이지로 이동한다.

[Feature/FE] 프로필 검색 기능 보완

---

backend/src/main/java/com/woowacourse/f12/config/WebConfig.java

- webConfig 내의 addFormatters 메소드 제거 (Converter bean 자동 등록)

[BE] converter에 대한 기능 리팩토링 

---

frontend/src/components/common/Chip/Chip.tsx
frontend/src/components/common/ProductSelect/ProductSelect.style.tsx
frontend/src/components/common/ProductSelect/ProductSelect.tsx
frontend/src/components/common/UserInfo/UserInfo.tsx
frontend/src/custom.d.ts
frontend/src/hooks/useInventory.tsx
frontend/src/index.tsx
frontend/src/mocks/data.ts
frontend/src/pages/Profile/Profile.tsx

- 카테고리 별로 상품 목록을 출력한다.
- 카테고리 별로 상품을 등록할 수 있다.
- 대표장비를 등록/수정할 수 있다.

[FE] 프로필 기능을 보완

---

frontend/src/components/ProfileCard/ProfileCard.tsx
frontend/src/components/common/ProductSelect/ProductSelect.tsx
frontend/src/constants/api.ts
frontend/src/hooks/useOtherInventory.tsx
frontend/src/pages/OtherProfile/OtherProfile.style.tsx
frontend/src/pages/OtherProfile/OtherProfile.tsx
frontend/src/pages/index.tsx

[Feature/FE] 다른 사람의 프로필 페이지 보기 기능

---

frontend/src/components/common/BarGraph/BarGraph.tsx

[Feature/FE] 통계 그래프 색상 수정

---

frontend/package.json

- package.json
- description 수정
- 링크 정보 수정

[Feature/FE] package.json 정보 수정

---

frontend/src/components/common/ReviewForm/ReviewForm.tsx

리뷰 작성 최대 길이 검증 수정
- 수정 함수에 검증 절차 추가
- textarea에 maxLength prop 추가

[Bugfix/FE] 리뷰 작성 최대 길이 검증 수정

---

frontend/src/components/common/BarGraph/BarGraph.tsx

[Bugfix/FE] 사용자 통계 그래프 버그 수정

---

frontend/src/components/common/ProductSelect/ProductSelect.style.tsx
frontend/src/components/common/ProductSelect/ProductSelect.tsx
frontend/src/components/common/SectionHeader/SectionHeader.style.tsx
frontend/src/pages/Profile/Profile.style.tsx
frontend/src/pages/Profile/Profile.tsx

[Bugfix/FE] 프로필 페이지에 섹션 제목 및 설명 추가

---

frontend/package.json
frontend/src/components/common/UserInfo/UserInfo.tsx
frontend/src/hooks/useOtherInventory.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/OtherProfile/OtherProfile.tsx
frontend/src/pages/common/ClosedRoutes/ClosedRoutes.tsx
frontend/src/pages/common/RegisterIncompleteRoute/RegisterCompleteRoute.tsx
frontend/src/pages/index.tsx

- 로그인 하고 추가정보 입력하지 않은 경우 다른 경로로 이동하지 못하고 다시 추가정보 페이지로 돌아오게 변경
- 프로필 페이지에서도 추가정보 없는 경우 제외하고 표시하도록 오류 수정

[Hotfix/FE] 추가정보 입력하지 않은 사용자의 경로 이동 방지 추가

---

backend/src/main/java/com/woowacourse/f12/config/WebConfig.java

- webConfig addFormatters 메소드 삭제

[Feature/BE] Sprint3에 대한 버퍼 해소

---

frontend/src/components/common/BarGraph/BarGraph.tsx

[FE] 통계 컴포넌트 코드 리팩토링

---

frontend/src/components/InventoryProductList/InventoryProductList.tsx
frontend/src/components/common/ProductSelect/ProductSelect.tsx
frontend/src/components/common/UserInfo/UserInfo.styled.tsx
frontend/src/components/common/UserInfo/UserInfo.tsx

- 대표 장비 삭제
- github icon 추가
- 상품 이동 링크 추가

[Feature/FE] 프로필 페이지 개선

---

frontend/src/mocks/data.ts
frontend/src/mocks/handlers.ts

API 모킹 추가 및 정리
- 종류 별로 API 분류해서 구분하고 정리 (순서 유의미, 주석 참고)
- 누락된 프로필 검색, 다른 사람 프로필 조회 API 추가

[Feature/FE] MSW API 모킹 핸들러 순서 정리 및 누락 핸들러 추가

---

frontend/src/assets/nextSign.svg
frontend/src/assets/prevSign.svg
frontend/src/components/ProfileCard/ProfileCard.style.tsx
frontend/src/components/ProfileCard/ProfileCard.tsx

- 프로필 카드의 상품에 상품 상세 페이지 이동 링크를 건다.
- 프로필 카드의 대표 장비 목록에 상품이 등록된 것을 우선적으로 표시한다.
- 프로필 카드의 margin 값을 조정한다.
- 프로필 카드의 화살표 모양을 이미지로 변경한다.

[Feature/FE] 프로필 카드 개선

---

backend/src/docs/asciidoc/products.adoc
backend/src/main/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductService.java
backend/src/main/java/com/woowacourse/f12/application/product/ProductService.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepository.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepositoryCustom.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/dto/request/product/ProductSearchRequest.java
backend/src/main/java/com/woowacourse/f12/presentation/product/ProductController.java
backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/product/ProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/product/ProductDocumentation.java
backend/src/test/java/com/woowacourse/f12/domain/product/ProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolverTest.java
backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java

[BE] 제품을 검색할 수 있는 기능 구현

---

backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/domain/review/ReviewRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/support/RepositorySupport.java

Repository 중복 코드를 RepositorySupport로 분리

[BE] QueryDSL 중복코드 제거

---

frontend/.storybook/main.js
frontend/src/components/ProductListSection/ProductListSection.stories.tsx
frontend/src/components/ReviewListSection/ReviewListSection.stories.tsx
frontend/src/components/SearchFilter/SearchFilter.stories.tsx
frontend/src/mocks/data.ts
frontend/src/pages/Products/Products.tsx

컴포넌트 prop 변경으로 발생하는 스토리북 컴포넌트 오류 해결

[Bugfix/FE] 스토리북 컴포넌트 오류 수정

---

backend/src/docs/asciidoc/products.adoc
backend/src/main/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductService.java
backend/src/main/java/com/woowacourse/f12/application/product/ProductService.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepository.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepositoryCustom.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/domain/review/ReviewRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/dto/request/product/ProductSearchRequest.java
backend/src/main/java/com/woowacourse/f12/presentation/product/ProductController.java
backend/src/main/java/com/woowacourse/f12/support/RepositorySupport.java
backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/product/ProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/product/ProductDocumentation.java
backend/src/test/java/com/woowacourse/f12/domain/product/ProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolverTest.java
backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java

- 제품 이름과 제품 카테고리로 검색하는 기능 구현
- QueryDSL 중복 코드 제거

[Feature/BE] 제품 검색 기능 구현

---

.github/workflows/backend.yml
backend/build.gradle

- build.gradle 에 sonarqube scanner 설정 추가
- gitHub Actions backend workflow 수정

[BE] github actions에서 정적 분석을 실행시키도록 한다

---

.github/workflows/backend.yml
backend/build.gradle

- build.gradle 에 sonarqube scanner 설정 추가
- gitHub Actions backend workflow 수정

[BE] github actions에서 SonarQube 정적 분석을 실행

---

.github/workflows/backend.yml

[BE] 소나큐브 정적 분석 commet를 데코레이션 한다

---

.github/workflows/backend.yml

- gitHub actions workflow 누락 내용 추가

[BugFix] gitHub actions workflow 누락 내용 추가

---

.github/workflows/backend.yml

- gitHub actions workflow에서 push 조건 삭제

[BugFix] gitHub actions workflow에서 push 조건 삭제

---

.github/workflows/backend.yml

- gitHub actions test report comment 삭제

[BugFix] gitHub actions test report comment 삭제

---

backend/src/main/java/com/woowacourse/f12/exception/internalserver/IllegalRequestLogTimerState.java
backend/src/main/java/com/woowacourse/f12/presentation/LogInterceptor.java
backend/src/main/java/com/woowacourse/f12/support/RequestLogTimer.java
backend/src/test/java/com/woowacourse/f12/presentation/ControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolverTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthInterceptorTest.java
backend/src/test/java/com/woowacourse/f12/support/RequestLogTimerTest.java

Co-authored-by:Youngyoon-1 <duddbs774@naver.com>
- 요청 처리 소요 시간 로깅 구현

[BE] 요청 처리 소요 시간 로깅 구현

---

frontend/src/index.tsx
frontend/src/pages/ProfileSearch/ProfileSearch.tsx

[Bugfix/FE] 프로필 검색 요청 시 잘못된 키워드 수정

---

frontend/src/pages/common/PageLayout/PageLayout.tsx

- 루트를 새로 렌더링 할 때 페이지 최상단으로 스크롤하도록 수정
- page layout 컴포넌트에 location.key에 의존하는 effect 훅 추가 해서 설정

[Feature/FE] 루트를 새로 렌더링 할 때 페이지 최상단으로 스크롤하도록 수정

---

frontend/src/components/common/HeaderNav/HeaderNav.tsx
frontend/src/constants/routes.ts
frontend/src/pages/index.tsx

- 타인의 프로필에서 상단바 내 프로필 링크 활성화 되는 오류를 수정
- 내 프로필의 경우 param으로 me를 추가해서 pathname을 아예 구분하도록 수정

[Bugfix/FE] 타인의 프로필에서 상단바 내 프로필 링크 활성화 되는 오류를 수정

---

frontend/src/components/DeskSetup/DeskSetup.style.tsx
frontend/src/components/DeskSetup/DeskSetup.tsx
frontend/src/components/DeskSetupCard/DeskSetupCard.style.tsx
frontend/src/components/DeskSetupCard/DeskSetupCard.tsx
frontend/src/components/Profile/InventoryProductList/InventoryProductList.style.tsx
frontend/src/components/Profile/InventoryProductList/InventoryProductList.tsx
frontend/src/components/Profile/UserInfo/UserInfo.style.tsx
frontend/src/components/Profile/UserInfo/UserInfo.tsx
frontend/src/mocks/data.ts
frontend/src/pages/Profile/Profile.style.tsx
frontend/src/pages/Profile/Profile.tsx

- 작성된 리뷰가 없는 경우 작성된 리뷰가 없다는 문구 출력
- 리뷰를 작성한 제품 목록을 grid layout으로 수정
- 내 프로필에서는 팔로우 버튼을 숨김처리
- 데스크 셋업 카드에서 긴 이미지가 늘어나는 현상 수정
- 데스크 셋업에 추가한 제품이 없는 경우 등록한 제품이 없다는 문구 출력

[BugFix/FE] 프로필 UI 버그 수정

---

backend/src/docs/asciidoc/error.adoc
backend/src/docs/asciidoc/members.adoc
backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/FollowingRepository.java
backend/src/main/java/com/woowacourse/f12/exception/ErrorCode.java
backend/src/main/java/com/woowacourse/f12/exception/badrequest/NotFollowingException.java
backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/FollowingRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java

[BE] 사용자를 unfollow 하는 기능 구현

---

frontend/src/components/Profile/ProfileSearchResult/ProfileSearchResult.style.tsx
frontend/src/components/Profile/ProfileSearchResult/ProfileSearchResult.tsx
frontend/src/components/common/HeaderNav/HeaderNav.tsx
frontend/src/constants/api.ts
frontend/src/constants/routes.ts
frontend/src/hooks/useSearch.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/ProfileSearch/ProfileSearch.tsx
frontend/src/pages/index.tsx

- 기존의 프로필 검색 페이지 재활용해서 팔로잉 페이지 구현
- 프로필 페이지에 섹센 헤더 추가

[Feature/FE] 팔로잉 페이지 UI 구현

---

backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/dto/response/review/ReviewWithAuthorPageResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/review/ReviewWithAuthorResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthArgumentResolver.java
backend/src/main/java/com/woowacourse/f12/presentation/review/ReviewController.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/review/ReviewPresentationTest.java

- DTO에 authorMatch 필드 추가
- AuthArgumentResolver에서 토큰이 없는 경우 예외 대신 null 반환하도록 수정

[Feature/BE] 제품 리뷰 목록 조회 시 수정 및 삭제 가능 여부 기능 구현

---

backend/src/docs/asciidoc/error.adoc
backend/src/docs/asciidoc/members.adoc
backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/FollowingRepository.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/domain/product/Product.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberWithProfileProductResponse.java
backend/src/main/java/com/woowacourse/f12/exception/ErrorCode.java
backend/src/main/java/com/woowacourse/f12/exception/badrequest/NotFollowingException.java
backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/FollowingRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java

[BE] 회원의 팔로워수를 보여주는 기능 추가

---

backend/build.gradle
backend/src/main/resources/log4j2/log4j2-main.xml
backend/src/main/resources/log4j2/log4j2-release.xml

- AsyncLogger에서 AsyncAppender 사용으로 변경

[BugFix/BE] AsyncLogger에서 AsyncAppender 사용으로 변경

---

backend/src/docs/asciidoc/members.adoc
backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/FollowingRepository.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/LoggedInMemberResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberPageResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberWithProfileProductResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthArgumentResolver.java
backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/AuthServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/FollowingRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java
backend/src/test/java/com/woowacourse/f12/support/FakeGitHubApiController.java
backend/src/test/java/com/woowacourse/f12/support/GitHubProfileFixtures.java
backend/src/test/java/com/woowacourse/f12/support/MemberFixtures.java

[BE] 회원의 follow 여부를 보여주는 기능 추가

---

frontend/src/components/DeskSetup/DeskSetup.tsx
frontend/src/components/DeskSetupCard/DeskSetupCard.tsx
frontend/src/components/Profile/InventoryProductList/InventoryProductList.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.tsx
frontend/src/components/common/Modal/Modal.style.tsx
frontend/src/constants/api.ts
frontend/src/contexts/ModalContextProvider.tsx
frontend/src/hooks/useModal.tsx
frontend/src/mocks/data.ts
frontend/src/mocks/handlers.ts
frontend/src/types/review.d.ts

- 사용자가 제품에 작성한 리뷰를 1:1로 조회하는 기능을 구현

[FE] 사용자가 제품에 작성한 리뷰를 1:1로 조회하는 기능을 구현

---

backend/src/docs/asciidoc/members.adoc
backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustom.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberPageResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberWithProfileProductResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java

- 회원이 팔로잉하는 사용자의 목록을 조회하는 api 구현

[BE] 팔로잉하는 사용자 목록을 조회 기능 구현

---

frontend/src/components/DeskSetup/DeskSetup.tsx
frontend/src/components/DeskSetupCard/DeskSetupCard.tsx
frontend/src/components/Profile/InventoryProductList/InventoryProductList.tsx
frontend/src/components/Profile/ProfileCard/ProfileCard.stories.tsx
frontend/src/components/Profile/ProfileCard/ProfileCard.style.tsx
frontend/src/components/Profile/ProfileCard/ProfileCard.tsx
frontend/src/components/Profile/ProfileSearchResult/ProfileSearchResult.tsx
frontend/src/components/Profile/UserInfo/UserInfo.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.tsx
frontend/src/components/common/Modal/Modal.style.tsx
frontend/src/constants/api.ts
frontend/src/contexts/ModalContextProvider.tsx
frontend/src/hooks/api/useDelete.tsx
frontend/src/hooks/useFollowing.tsx
frontend/src/hooks/useModal.tsx
frontend/src/hooks/useReviews.tsx
frontend/src/hooks/useSearch.tsx
frontend/src/mocks/data.ts
frontend/src/mocks/handlers.ts
frontend/src/pages/ProfileSearch/ProfileSearch.tsx
frontend/src/types/profile.d.ts
frontend/src/types/review.d.ts

[Feature/FE] 사용자 팔로우 기능 구현

---

frontend/src/components/DeskSetup/DeskSetup.tsx
frontend/src/components/DeskSetupCard/DeskSetupCard.tsx
frontend/src/components/Profile/InventoryProductList/InventoryProductList.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.tsx
frontend/src/components/common/Modal/Modal.style.tsx
frontend/src/constants/api.ts
frontend/src/contexts/ModalContextProvider.tsx
frontend/src/hooks/useModal.tsx
frontend/src/mocks/data.ts
frontend/src/mocks/handlers.ts
frontend/src/types/review.d.ts

[Feature/FE] 사용자가 제품에 작성한 리뷰를 1:1로 조회하는 기능을 구현

---

frontend/src/hooks/api/usePost.tsx
frontend/src/hooks/useFollowing.tsx

- 팔로우 요청시 불필요한 payload가 전송되는 오류 수정

[Bugfix/FE] 팔로우 요청시 불필요한 payload가 전송되는 오류 수정

---

backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java

- 사용자 팔로우 언팔로우 Transactional 적용되지 않는 현상 수정

[Bugfix/BE] 사용자 팔로우 언팔로우 Transactional 적용되지 않는 현상 수정

---

frontend/src/hooks/api/usePost.tsx

body가 없는 POST 요청에서 발생하는 오류 임시 해결

[Bugfix/FE] body가 없는 POST 요청에서 발생하는 오류 임시 해결

---

frontend/public/index.html
frontend/src/style/GlobalStyles.tsx

폰트에 대한 다이나믹 서브셋을 적용
https://github.com/orioncactus/pretendard

[FE] 폰트에 대한 다이나믹 서브셋을 적용

---

frontend/src/hooks/useDebouce.tsx
frontend/src/pages/Products/Products.tsx
frontend/src/pages/ProfileSearch/ProfileSearch.tsx

[FE] 검색에서 불필요하게 자주 요청을 보내지 않도록 처리

---

backend/build.gradle
backend/src/docs/asciidoc/members.adoc
backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/Following.java
backend/src/main/java/com/woowacourse/f12/domain/member/FollowingRepository.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustom.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberPageResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/AuthServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/FollowingRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/FollowingTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java

[BE] 팔로우 기능에 대한 리뷰를 적용한다.

---

frontend/src/components/Product/ProductCard/ProductCard.tsx
frontend/src/components/common/LazyImage/LazyImage.style.tsx
frontend/src/components/common/LazyImage/LazyImage.tsx
frontend/src/hooks/useLazyImage.tsx

- useLazyImage hook
- LazyImage 컴포넌트

[FE] 이미지 lazy loading 구현

---

frontend/src/components/common/LazyImage/LazyImage.tsx

[FE] 불필요한 console.log 제거

---

frontend/webpack.common.js

배포 시에 bundleAnalyzer가 실행되지 않도록 주석 처리

[FE/Bugfix] 배포 시에 bundleAnalyzer가 실행되지 않도록 주석 처리

---

frontend/src/components/Profile/InventoryProductList/InventoryProductList.tsx
frontend/src/pages/Profile/Profile.tsx

변경 전과 변경 후의 상태를 비교하여 동일할 경우 API 요청을 보내지 않는다.

[FE] 데스크 셋업 변경 시 불필요한 API 요청을 보내지 않는다.

---

frontend/src/components/Product/ProductCard/ProductCard.tsx
frontend/src/components/Profile/ProfileCard/ProfileCard.tsx
frontend/src/hooks/useLazyImage.tsx

- ProfileCard, ProductCard memo 적용

[FE] 불필요한 리렌더링이 발생하지 않도록 최적화 진행

---

backend/build.gradle
backend/src/docs/asciidoc/members.adoc
backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/Following.java
backend/src/main/java/com/woowacourse/f12/domain/member/FollowingRepository.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustom.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberPageResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/AuthServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/FollowingRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/FollowingTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java

-  follower, following 명칭 통일 -> 이에 따라 uri도 변경됨
- MemberPageResponse 정적 메소드 리팩토링
- API 문서 리팩토링
- `@Nullable`에서 발생하는 warning 제거

[Feature/BE] 팔로우 기능에 대한 리뷰를 적용한다.

---

frontend/src/constants/api.ts

- '/members/me/followees' => '/members/me/followings'로 변경

[Bugfix/FE] Following Api Endpoint 주소 변경

---

backend/src/main/resources/application-performance.yml

[BE] performance yml를 추가한다

---

backend/src/main/resources/application-performance.yml
backend/src/main/resources/application.yml

[Feature/BE] performance yml를 추가한다

---

frontend/src/components/DeskSetupCard/DeskSetupCard.style.tsx
frontend/src/components/DeskSetupCard/DeskSetupCard.tsx
frontend/src/components/Profile/InventoryProductList/InventoryProductList.tsx
frontend/src/constants/api.ts
frontend/src/hooks/useInventory.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Profile/Profile.style.tsx
frontend/src/pages/Profile/Profile.tsx

[FE] 프로필 페이지에 리뷰 목록을 출력하는 기능 구현

---

frontend/src/components/DeskSetup/DeskSetup.tsx
frontend/src/components/DeskSetupCard/DeskSetupCard.style.tsx
frontend/src/components/DeskSetupCard/DeskSetupCard.tsx
frontend/src/components/Profile/InventoryProductList/InventoryProductList.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.tsx
frontend/src/components/Review/ReviewListSection/ReviewListSection.tsx
frontend/src/constants/api.ts
frontend/src/hooks/useInventory.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Profile/Profile.style.tsx
frontend/src/pages/Profile/Profile.tsx

- 프로필 페이지 애니메이션 적용
- 프로필 페이지에 해당 사용자가 작성한 리뷰 목록 출력
- 리뷰를 작성한 제품 리스트와 작성한 리뷰 리스트를 탭 버튼으로 전환

[Feature/FE] 프로필 페이지에 리뷰 목록을 출력하는 기능 구현

---

frontend/src/components/Profile/ProfileCard/ProfileCard.tsx
frontend/src/components/Profile/UserInfo/UserInfo.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.stories.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.tsx
frontend/src/constants/link.ts

- &s search param을 사용하여 이미지 크기 최적화

[FE] GitHub 프로필 이미지 크기를 최적화

---

backend/src/main/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductService.java
backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProduct.java
backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepository.java
backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProducts.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java

- @BatchSize와 Fetch EAGER를 제거한다

[BE] @BatchSize와 Fetch EAGER를 제거한다

---

backend/src/docs/asciidoc/auth.adoc
backend/src/main/java/com/woowacourse/f12/config/WebConfig.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthController.java
backend/src/test/java/com/woowacourse/f12/acceptance/AuthAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthControllerTest.java

- WebConfig에서 credential 을 true로 설정

[BE] CORS 크레덴셜을 허용한다.

---

frontend/cypress/e2e/spec.cy.ts
frontend/src/hooks/useInventory.tsx

- useSessionStorage => useContext로 수정
- cypress 오류 수정

[Bugfix] useSessionStorage 사용 삭제 및 cypress 오류 수정

---

backend/src/main/java/com/woowacourse/f12/config/WebConfig.java

- WebConfig에서 credential 을 true로 설정

[BE] CORS 크레덴셜 추가

---

backend/src/main/java/com/woowacourse/f12/config/WebConfig.java

- WebConfig에서 credential 을 true로 설정

[BugFix/BE] CORS 크레덴셜 추가

---

frontend/webpack.common.js

웹팩 설정 정리
- css 관련 설정 제거
- 불필요한 확장자 설정 제거
- svgr 설정 일부 수정

[Chore/FE] 불필요한 웹팩 설정 제거

---

backend/src/main/java/com/woowacourse/f12/config/WebConfig.java

- WebConfig CORS 설정에 exposeHeaders에 Set-Cookie 헤더 추가

[BugFix/BE] CORS exposeHeaders에 Set-Cookie 추가

---

backend/src/main/java/com/woowacourse/f12/domain/review/ReviewRepository.java

- review 페이징하는 레포지토리 메서드에서 Fetch join을 사용하도록 구현

[Feature/BE] Review 페이징 조회 시 2N+1 문제 fetch join으로 해결

---

backend/src/main/resources/application.yml

- application.yml에 Cookie same-site None으로 설정

[BugFix/BE] cookie samesite none 설정

---

backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthController.java
backend/src/main/resources/application.yml

- 기존에 Cookie 객체를 ResponseCookie로 대체해서 SameSite를 None으로 추가

[BugFix/BE] 쿠키 SameSite를 None으로 설정

---

frontend/src/hooks/api/useGet.tsx
frontend/src/hooks/useAuth.tsx

- 로그인 get 요청에 대해서 withCrendentials 설정 추가

[Bugfix] 로그인 요청에 withCredential 설정을 추가

---

frontend/src/hooks/useAuth.tsx

- 로그아웃 시에도 리프레시 토큰을 보내도록 withCredentials 설정

[Bugfix/FE] 로그아웃 시에도 리프레시 토큰을 보내도록 withCredentials 설정

---

frontend/src/hooks/useInventory.tsx
frontend/src/hooks/useReviews.tsx

[FE] 리뷰 조회 시 정렬 조건 제거

---

frontend/src/hooks/useInventory.tsx
frontend/src/hooks/useReviews.tsx

- useInventory, useReviews `sort: 'createdAt,desc'` 제거

[Feature/FE] 리뷰 조회 시 정렬 조건 제거

---

frontend/src/hooks/api/useAxios.tsx
frontend/src/mocks/handlers.ts

- 현재 오류 코드가 잘못 설정 되어있어서 silent refresh가 제대로 이루어지지 않음
- 40104 => 40101로 수정

[Hotfix] 토큰 silent refresh를 위한 오류 코드 수정

---

backend/build.gradle
backend/src/main/java/com/woowacourse/f12/application/auth/GitHubOauthClient.java
backend/src/main/java/com/woowacourse/f12/exception/internalserver/OauthProcessingException.java
backend/src/test/java/com/woowacourse/f12/application/auth/AuthServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/GitHubOauthClientTest.java
backend/src/test/java/com/woowacourse/f12/support/FakeGitHubApiController.java

- WebClient를 HttpClient로 변경
- webFlux 의존성 제거

feat: WebClient를 HttpClient로 교체

---

backend/src/test/java/com/woowacourse/f12/acceptance/support/DatabaseCleanup.java
backend/src/test/java/com/woowacourse/f12/acceptance/support/EscapeSqlUtil.java

테스트 코드이지만, SQL을 문자열 방식을 통해서 직접 생성하는 방식 변경

[BE] DatabaseCleanup sql 생성 방식 변경

---

frontend/src/components/Profile/ProfileCard/ProfileCard.tsx
frontend/src/components/Profile/ProfileSearchResult/ProfileSearchResult.tsx
frontend/src/components/common/BarGraph/BarGraph.tsx
frontend/src/components/common/Chip/Chip.tsx
frontend/src/components/common/ChipFilter/ChipFilter.tsx
frontend/src/components/common/SectionHeader/SectionHeader.tsx
frontend/src/constants/header.ts
frontend/src/constants/profile.ts
frontend/src/hooks/useUrlSyncState.tsx
frontend/src/pages/Products/Products.tsx
frontend/src/pages/ProfileSearch/ProfileSearch.tsx
frontend/src/types/api.d.ts
frontend/src/types/auth.d.ts
frontend/src/types/product.d.ts
frontend/src/types/profile.d.ts
frontend/src/types/review.d.ts

- 타입스크립트 리팩토링
- 타입스크립트 개선 과정에서 발견된 리팩토링 사항 일부 적용

[FE] 타입 리팩토링

---

backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/review/ReviewControllerTest.java

[BugFix/BE] UniqueConstraint 어노테이션 import

---

backend/src/docs/asciidoc/auth.adoc
backend/src/main/java/com/woowacourse/f12/application/auth/AuthService.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/dto/response/auth/AdminLoginResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthController.java
backend/src/test/java/com/woowacourse/f12/application/auth/AuthServiceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthControllerTest.java

[BE] 어드민 로그인 api 구현

---

frontend/webpack.dev.js

[Bug-fix/FE] dev 환경 github client id 변경

---

backend/src/docs/asciidoc/products.adoc
backend/src/main/java/com/woowacourse/f12/application/product/FindPopularProductCallback.java
backend/src/main/java/com/woowacourse/f12/application/product/PopularProductCriteriaDefinition.java
backend/src/main/java/com/woowacourse/f12/application/product/PopularProductCriteriaDefinitionImpl.java
backend/src/main/java/com/woowacourse/f12/application/product/PopularProductStrategy.java
backend/src/main/java/com/woowacourse/f12/application/product/ProductService.java
backend/src/main/java/com/woowacourse/f12/application/product/ShufflingPopularProductStrategy.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepository.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepositoryCustom.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/dto/response/PopularProductsResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/product/ProductController.java
backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/product/FakeFindPopularProductCallback.java
backend/src/test/java/com/woowacourse/f12/application/product/PopularProductStrategyTest.java
backend/src/test/java/com/woowacourse/f12/application/product/ProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/product/ProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java

[BE] 인기 제품 조회 API 구현

---

backend/src/main/java/com/woowacourse/f12/config/DatasourceConfig.java
backend/src/main/java/com/woowacourse/f12/support/DataSourceType.java
backend/src/main/java/com/woowacourse/f12/support/ReplicationRoutingDataSource.java
backend/src/main/resources/application.yml
backend/src/test/java/com/woowacourse/f12/acceptance/AcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/config/DatasourceConfigTest.java
backend/src/test/java/com/woowacourse/f12/config/TestDataSourceConfig.java
backend/src/test/java/com/woowacourse/f12/config/TransactionTestService.java

- DB replication에 대한 DataSource를 설정한다

[BE] DB replication에 대한 DataSource를 설정한다

---

frontend/src/assets/left_arrow.svg
frontend/src/assets/nextSign.svg
frontend/src/assets/right_arrow.svg
frontend/src/components/Profile/ProfileCard/ProfileCard.tsx

- 좌우 화살표 이미지를 각각 넣어주었습니다.
- 아이패드 사파리에서 테스트 및 확인 완료했습니다.

[BugFix/FE] 사파리 브라우저에서 좌우측 프로필 카드 버튼이 동일하게 렌더링되는 문제를 수정

---

frontend/cypress/e2e/spec.cy.ts
frontend/cypress/support/commands.ts
frontend/src/components/Product/ProductCard/ProductCard.style.tsx
frontend/src/components/Product/ProductCard/ProductCard.tsx
frontend/src/components/Product/ProductListSection/ProductListSection.style.tsx
frontend/src/components/Product/ProductListSection/ProductListSection.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.style.tsx
frontend/src/components/common/ChipFilter/ChipFilter.tsx
frontend/src/components/common/HeaderLogo/HeaderLogo.tsx
frontend/src/components/common/InfiniteScroll/InfiniteScroll.tsx
frontend/src/components/common/LazyImage/LazyImage.tsx
frontend/src/components/common/Rating/Rating.style.tsx
frontend/src/components/common/Rating/Rating.tsx
frontend/src/components/common/ReviewCount/ReviewCount.tsx
frontend/src/components/common/SearchBar/SearchBar.style.tsx
frontend/src/components/common/SearchBar/SearchBar.tsx
frontend/src/components/common/SearchFilter/SearchFilter.tsx
frontend/src/components/common/SectionHeader/SectionHeader.style.tsx
frontend/src/components/common/Select/Select.tsx
frontend/src/pages/Products/Products.style.tsx
frontend/src/pages/Products/Products.tsx
frontend/src/style/GlobalStyles.tsx
frontend/src/style/ResetCss.tsx

- 제품 목록 탐색 및 검색, 카테고리 적용 및 정렬 기준 적용 과정에 접근성 적용
- 제품 목록, 제품 카드, 리뷰 카드, 평점, 리뷰 개수 컴포넌트에 접근성 적용
- 제품 목록 로딩 시 스크린리더 안내문구 추가

[FE] 제품 탐색 및 검색 로직에 접근성 구현

---

frontend/src/components/common/BottomNavigation/BottomNavigation.style.tsx
frontend/src/components/common/BottomNavigation/BottomNavigation.tsx
frontend/src/components/common/HeaderLogo/HeaderLogo.style.tsx
frontend/src/components/common/HeaderLogo/HeaderLogo.tsx
frontend/src/components/common/HeaderNav/HeaderNav.style.tsx
frontend/src/components/common/HeaderNav/HeaderNav.tsx
frontend/src/pages/common/PageLayout/PageLayout.tsx

- 상단, 하단 메뉴바 태그 통일, 레이블 추가
- ul로 감싸주고 li로 만들어서 목록화

[FE] 상하단 메뉴바 접근성 개선

---

frontend/src/hooks/api/useGetMany.tsx
frontend/src/hooks/useSearch.tsx
frontend/src/pages/Products/Products.tsx

무한 스크롤 로딩정보 관련 메시지 추가
추가로 로딩할 수 있으면 방법을 알려줌

무한 스크롤 로딩정보 관련 메시지 추가

---

frontend/src/components/common/ErrorPlaceholder/ErrorPlaceholder.tsx
frontend/src/components/common/NoDataPlaceholder/NoDataPlaceholder.tsx

제품 목록 불러오기 실패나 항목 없을 때 스크린 리더 alert 추가
role="alert" 추가해서 마운트 시 스크린리더가 읽어줌

[FE] 제품 목록 불러오기 실패나 항목 없을 때 스크린 리더 alert 추가

---

frontend/src/pages/common/PageLayout/PageLayout.style.tsx
frontend/src/pages/common/PageLayout/PageLayout.tsx

- 탭 이동 시 포커스 border가 표시되는 문제 수정

[FE] 탭 이동 시 포커스 border가 표시되는 문제 수정

---

frontend/public/index.test.html
frontend/webpack.common.js
frontend/webpack.prod.js
frontend/webpack.test.js

```html
<meta name="robots" content="noindex" />
```
테스트 서버와 본 서버의 webpack 설정 분기

[FE] test 서버는 검색엔진에서 검색되지 않도록 robot 메타 태그 추가

---

frontend/src/mocks/handlers.ts

[FE] 리뷰 작성, 수정, 삭제 모킹 오류를 해결

---

frontend/src/components/common/HeaderNav/HeaderNav.tsx

- 모바일 페이지 메인 로고에 aria-label 속성 부여

[FE] 메인 로고 접근성 향상

---

frontend/public/index.html
frontend/src/hooks/useUrlSyncState.tsx
frontend/src/pages/common/PageLayout/PageLayout.tsx

document title을 설정하고 구글 애널리틱스를 추가
제품 검색 페이지 제목 오류 해결

[FE] document title을 설정하고 구글 애널리틱스를 추가

---

frontend/src/constants/api.ts
frontend/src/hooks/usePopularProducts.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Home/Home.tsx

- 인기 제품 API 주소를 변경
- 인기 제품 조회를 위한 훅 추가
- 인기 제품 API 모킹

[FE] 인기제품 API 주소 변경

---

backend/src/main/resources/db/migration/V1__init.sql
backend/src/main/resources/db/migration/V2.0__modify_member_role_column.sql
backend/src/main/resources/db/migration/V2.1__update_member_role_admin.sql
backend/src/main/resources/db/migration/V2.2__modify_member_career_level_column.sql
backend/src/main/resources/db/migration/V2.3__modify_member_job_type_column.sql
backend/src/main/resources/db/migration/V3.0__modify_product_category_column.sql
backend/src/main/resources/db/migration/V4.0__modify_inventory_product_member_id_column.sql
backend/src/main/resources/db/migration/V4.1__modify_inventory_product_product_id_column.sql
backend/src/main/resources/db/migration/V4.2__modify_inverntory_product_selected_column.sql
backend/src/main/resources/db/migration/V5.0__modify_following_following_id_column.sql

[BE] DB 컬럼을 flyway 버전별로 수정한다.

---

frontend/src/components/Profile/InventoryProductList/InventoryProductList.style.tsx
frontend/src/components/Profile/ProfileCard/ProfileCard.style.tsx
frontend/src/components/Profile/ProfileCard/ProfileCard.tsx
frontend/src/components/Profile/UserInfo/UserInfo.style.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.style.tsx
frontend/src/components/Review/ReviewForm/ReviewForm.style.tsx
frontend/src/components/common/CategoryNav/CategoryNav.style.tsx
frontend/src/components/common/HeaderNav/HeaderNav.style.tsx
frontend/src/components/common/InfiniteScroll/InfiniteScroll.tsx
frontend/src/components/common/SectionHeader/SectionHeader.style.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Profile/Profile.style.tsx
frontend/src/pages/Register/Register.style.tsx

[FE] 스타일이 통일되지 않은 부분들을 통일

---

backend/build.gradle
backend/src/main/resources/db/migration/V1__init.sql

[Bugfix/BE] flyway mysql 의존성 추가

---

frontend/src/components/Product/ProductListSection/ProductListSection.style.tsx
frontend/src/components/Product/ProductListSection/ProductListSection.tsx

[Bugfix/FE] 제품 정렬 스타일 오류 수정

---

frontend/src/components/common/BarGraph/BarGraph.tsx

[FE] 그래프의 바가 지속적으로 렌더링 되는 문제 수정

---

README.md

[DOCS] README 업데이트

---

frontend/package-lock.json
frontend/package.json

[Chore] 버전을 올림

---

frontend/src/components/Profile/ProfileCard/ProfileCard.style.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.style.tsx
frontend/src/mocks/data.ts

리뷰카드와 프로필 카드에서 높이가 긴 이미지가 잘리는 오류 수정

[Hotfix/FE] 리뷰카드와 프로필 카드에서 높이가 긴 이미지가 잘리는 오류 수정

---

admin/.gitignore
admin/src/App.jsx
admin/src/components/Button.jsx
admin/src/components/InsertProduct.jsx
admin/src/components/Main.jsx
admin/src/components/Product.jsx
admin/src/components/ProductCategorySelect.jsx

제품 추가 시 카테고리 오류 추가
전체적인 스타일 수정

[Hotfix/admin] 오류 수정 및 스타일 추가

---

frontend/src/hooks/api/useCache.tsx

프로필 페이지에서 데스크 셋업 변경 시 refetch가 되지 않는 오류 해결
캐시키 설정 오류 문제 해결

[Hotfix/FE] 프로필 페이지에서 데스크 셋업 변경 시 refetch가 되지 않는 오류 해결

---

backend/src/main/resources/db/migration/V1_0__init.sql
backend/src/main/resources/db/migration/V6_0__remove_fk_constraint_review_and_product.sql
backend/src/main/resources/db/migration/V6_1__remove_fk_constraint_inventory_product_and_product.sql

- FK 관계 제약조건을 flyway로 제거할 수 있도록 함

[BE] MySQL 환경에서 FK 설정으로 인한 제품에 대한 리뷰 생성시 발생하는 동시성 이슈를 해결한다

---

backend/src/main/resources/db/migration/V1_0__init.sql
backend/src/main/resources/db/migration/V6_0__remove_fk_constraint_review_and_product.sql
backend/src/main/resources/db/migration/V6_1__remove_fk_constraint_inventory_product_and_product.sql

자세한 내용은 이슈에 포함시켰습니다. 확인해주시고 더 좋은 방법이 있거나 현재 해결한 방법에 대해서 의문이 있다면 코멘트 남겨주시길 바랍니다
- flyway로 Review 테이블에 Product FK Constraint 제거
- flyway로 InventoryProduct 테이블에 Product FK Constraint 제거

[Bugfix/BE] MySQL 환경에서 FK 설정으로 인한 제품에 대한 리뷰 생성시 발생하는 동시성 이슈를 해결

---

frontend/package-lock.json
frontend/package.json

[Refactor/FE] 불필요한 babel cli 패키지 제거

---

frontend/src/components/Review/ReviewCard/ReviewCard.stories.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.tsx
frontend/src/components/Review/ReviewListSection/ReviewListSection.tsx
frontend/src/pages/Home/Home.tsx
frontend/src/pages/Profile/Profile.tsx

리뷰 카드가 다양한 상황에서 다른 모양으로 렌더링 되는 로직이 복잡
해당 컴포넌트를 복합 컴포넌트로 변경하고 필요에 따라 자식 컴포넌트에 컨텍스트를 사용해서 부모의 상태 일부를 전달하도록 변경

[Refactor/FE] 리뷰 카드를 복합 컴포넌트로 분리
