woowacourse-teams/2022-f12

backend/src/main/java/com/woowacourse/f12/config/CustomPageableHandlerArgumentResolver.java
backend/src/main/java/com/woowacourse/f12/config/WebConfig.java
backend/src/main/java/com/woowacourse/f12/exception/InvalidPageSizeException.java
backend/src/main/java/com/woowacourse/f12/presentation/CustomPageableHandlerArgumentResolver.java

- PageableHandlerMethodArgumentResolver 를 상속 받아 페이징 요청 크기가 최대 제한 크기를 넘어가면 예외를 발생시켰다.

[BE] 페이징 요청의 크기가 최대 제한 크기를 넘어갔을 때 예외를 발생시키는 기능 추가

---

backend/src/main/java/com/woowacourse/f12/application/KeyboardService.java
backend/src/main/java/com/woowacourse/f12/domain/Keyboard.java
backend/src/main/java/com/woowacourse/f12/domain/KeyboardRepository.java
backend/src/main/java/com/woowacourse/f12/dto/response/KeyboardPageResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/KeyboardResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/KeyboardController.java
backend/src/test/java/com/woowacourse/f12/acceptance/KeyboardAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/KeyboardServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/KeyboardRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/ReviewRepositoryTest.java

- 키보드 목록을 Pageable을 사용해서 페이징 처리하여 조회했다.
- rating 필드의 값을 매핑할 때 `AVG` sql 집계함수 사용으로 null이 반환되는 이슈로 `IFNULL(AVG(r.rating), 0)`을 사용하여 기본 값을 0으로 지정했다.
- 정렬 조건
- 미정렬
- 평점 높은 순
- 리뷰 많은 순

[BE] 키보드 목록을 페이징하여 조회한다.

---

backend/src/main/java/com/woowacourse/f12/config/WebConfig.java
backend/src/test/java/com/woowacourse/f12/config/WebConfigTest.java

- 모든 origin에 대해 CORS를 허용하도록 설정했다.
- origin이 확정되고 나면(프론트엔드 배포 이후) 허용된 origin 설정을 반드시 바꿔주어야 한다.

[BE] CORS를 임시로 허용한다.

---

backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
backend/src/main/java/com/woowacourse/f12/presentation/ReviewController.java
backend/src/main/resources/application.yml
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/ReviewControllerTest.java
backend/src/test/resources/application.yml

- 프론트엔드에서 지정한 API 주소와 다른 URL 수정
- 프로덕션에서 로컬 인메모리 h2 데이터베이스를 사용하도록 설정
- 테스트 설정 분리
- 임베디드 h2 데이터베이스를 사용하도록 설정
- 예상하지 못한 예외가 발생할 경우 서버에 로그를 남기도록 하는 기능 구현

[BE] 프론트엔드와 연결을 위한 설정 완료

---

backend/src/main/java/com/woowacourse/f12/presentation/CustomPageableHandlerMethodArgumentResolver.java
backend/src/test/java/com/woowacourse/f12/presentation/CustomPageableHandlerMethodArgumentResolverTest.java
backend/src/test/java/com/woowacourse/f12/presentation/KeyboardControllerTest.java

- 페이징 조회 요청에서 size 값 null을 체크하고 기본값으로 지정되도록 수정했다.
- 스프링에서 제공하는 기본 값은 page=0, size=20 이다.

[BE] 페이징 조회 요청에서 size 값 null 체크

---

backend/src/main/java/com/woowacourse/f12/application/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/Review.java
backend/src/main/java/com/woowacourse/f12/domain/ReviewRepository.java
backend/src/main/java/com/woowacourse/f12/dto/request/ReviewRequest.java
backend/src/main/java/com/woowacourse/f12/dto/response/ReviewResponse.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/KeyboardRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/ReviewRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/ReviewControllerTest.java
backend/src/test/java/com/woowacourse/f12/support/ReviewFixtures.java

- 리뷰 -> 키보드 ManyToOne 단방향 매핑
- fetch Lazy 로딩 옵션 추가
- 리뷰에서 productId 필드 제거
- 리뷰 페이징 조회에서 JPQL 직접 작성

[BE] 리뷰 도메인과 키보드 도메인 연관관계 추가

---

backend/src/main/java/com/woowacourse/f12/application/ReviewService.java
backend/src/main/java/com/woowacourse/f12/dto/response/KeyboardForReviewResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/ReviewWithProductPageResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/ReviewWithProductResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/ReviewController.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/ReviewControllerTest.java

- 키보드 정보를 담은 리뷰 response DTO를 추가했다.
- 해당 response의 페이지를 가지는 새로운 페이지 DTO를 추가했다.
- 특정 조건 없이 전체 리뷰를 조회하는 api의 응답 타입을 새로 만든 DTO로 변경했다.

[BE] 키보드 정보가 필요한 리뷰 DTO 생성

---

backend/src/main/java/com/woowacourse/f12/exception/InvalidPageNumberFormatException.java
backend/src/main/java/com/woowacourse/f12/exception/InvalidPageSizeFormatException.java
backend/src/main/java/com/woowacourse/f12/presentation/CustomPageableHandlerMethodArgumentResolver.java
backend/src/test/java/com/woowacourse/f12/presentation/CustomPageableHandlerMethodArgumentResolverTest.java

- 페이지 번호가 숫자 형식이 아닌 경우 예외 발생하도록 구현
- 페이지 크기가 숫자 형식이 아닌 경우 예외 발생하도록 구현
- null 인 경우 먼저 처리하여 정규표현식 검증에서 NPE 가 발생하지 않도록 구현

[BE] 페이지 조회 요청에서 NumberFormat 체크하여 예외 처리하도록 수정

---

.github/workflows/backend.yml

- build workflow가 main, release 브랜치에 PR 및 push 될 때만 작동하도록 YAML 파일을 수정했다.

[HotFix] backend build workflow 수정

---

backend/src/main/java/com/woowacourse/f12/application/AuthService.java

- AuthService에 `@Transactional(readOnly = true)`가 달려 있어 데이터베이스에 생성, 수정 작업을 해야 하는 `login` 메서드에서 읽기 전용 트랜잭션이 열리는 오류를 수정

[BE] 인증 과정에서 읽기 전용 트랜잭션이 적용되는 오류 수정

---

backend/src/main/java/com/woowacourse/f12/config/WebConfig.java
backend/src/main/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolver.java

- `CustomPageableArgumentResolver`를 스프링 빈으로 등록
- `WebConfig`에서 `HandlerInterceptor` 타입과 `HandlerMethodArgumentResolver` 타입의 빈을 리스트로 주입받도록 수정
- 주입받은 빈들의 리스트를 각각 Interceptor와 Resolver로 등록

[BE] Interceptor와 Resolver를 스프링 빈으로 만들어 한 번에 주입받아 등록하도록 변경

---

backend/src/main/java/com/woowacourse/f12/presentation/AuthArgumentResolver.java
backend/src/main/java/com/woowacourse/f12/presentation/AuthInterceptor.java
backend/src/main/java/com/woowacourse/f12/presentation/LoginRequired.java
backend/src/main/java/com/woowacourse/f12/presentation/ReviewController.java
backend/src/main/java/com/woowacourse/f12/presentation/VerifiedMember.java

- 기존에 로그인이 필요한 메서드에 붙이는 어노테이션 이름(`@Auth`)이 직관적이지 않아 로그인이 필요하다는 의미를 직관적으로 담은 `@LoginRequired`로 수정
- 로그인한 회원 정보를 가져오는 어노테이션 이름(`@AuthPrincipal`) 역시 직관적이도록 `@VerifiedMember`로 수정

[BE] 로그인이 필요한 메서드에 붙이는 어노테이션 명 수정

---

backend/src/main/java/com/woowacourse/f12/application/GitHubOauthClient.java

- GitHub에 access token을 요청할 때 `accept` 값을 넣지 않으면 `x-www-urlencoded` 타입으로 응답하는데 반해 응답값 파싱은 `application/json`으로 하고 있었음. 따라서 access token 요청 시 `accept: application/json`을 넣어줌

[BugFix] GitHub에 access token 요청할 때 JSON 형태로 요청하도록 수정

---

backend/src/main/java/com/woowacourse/f12/application/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/Review.java
backend/src/main/java/com/woowacourse/f12/dto/request/ReviewRequest.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/ReviewDocumentation.java
backend/src/test/java/com/woowacourse/f12/domain/KeyboardRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/ReviewRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/ReviewControllerTest.java
backend/src/test/java/com/woowacourse/f12/support/ReviewFixtures.java

- `Review`와 `Member` 사이에 `@ManyToOne` 단방향 연관관계를 맺어줌(`Review` -> `Member`)
- 서비스의 리뷰 작성 메서드에서 회원을 조회해 온 뒤 리뷰에 매핑해주고 저장하는 로직 추가

[BE] 리뷰 작성 시 리뷰에 작성자 정보를 함께 저장

---

backend/src/docs/asciidoc/index.adoc
backend/src/docs/asciidoc/members.adoc
backend/src/main/java/com/woowacourse/f12/application/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/InventoryProduct.java
backend/src/main/java/com/woowacourse/f12/domain/InventoryProductRepository.java
backend/src/main/java/com/woowacourse/f12/domain/Member.java
backend/src/main/java/com/woowacourse/f12/dto/request/ProfileProductRequest.java
backend/src/main/java/com/woowacourse/f12/exception/InventoryItemNotFoundException.java
backend/src/main/java/com/woowacourse/f12/presentation/MemberController.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/support/RestAssuredRequestUtil.java
backend/src/test/java/com/woowacourse/f12/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/MemberDocumentation.java
backend/src/test/java/com/woowacourse/f12/presentation/MemberControllerTest.java

- InventoryProduct의 id를 이용해서 대표 장비를 업데이트한다.
- InventoryProduct는 MemberId를 간접 참조한다.
- InventoryProduct는 Keyboard를 다대일 단방향 매핑한다.
- 대표 장비를 업데이트할 때 selected로 들어온 요청은 모두 isSelected를 true로 변경하고, unselected로 들어온 요청은 모두 false로 변경한다.

[BE] 대표 장비를 업데이트 하는 기능 구현

---

backend/src/docs/asciidoc/reviews.adoc
backend/src/main/java/com/woowacourse/f12/application/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/Keyboard.java
backend/src/main/java/com/woowacourse/f12/domain/Member.java
backend/src/main/java/com/woowacourse/f12/domain/Review.java
backend/src/main/java/com/woowacourse/f12/exception/ForbiddenMemberException.java
backend/src/main/java/com/woowacourse/f12/exception/NotAuthorException.java
backend/src/main/java/com/woowacourse/f12/exception/ReviewNotFoundException.java
backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
backend/src/main/java/com/woowacourse/f12/presentation/ReviewController.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/support/RestAssuredRequestUtil.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/ReviewDocumentation.java
backend/src/test/java/com/woowacourse/f12/domain/ReviewRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/ReviewTest.java
backend/src/test/java/com/woowacourse/f12/presentation/AuthInterceptorTest.java
backend/src/test/java/com/woowacourse/f12/presentation/ReviewControllerTest.java
backend/src/test/java/com/woowacourse/f12/support/MemberFixtures.java

- 리뷰 삭제 요청 시 로그인한 회원과 리뷰 작성자가 동일하면 리뷰를 삭제하는 기능 구현
- 리뷰 - 회원이 지연 로딩으로 설정되어 있기 때문에 프록시로 인한 동등성 비교 문제가 발생
- equals 재정의 방식을 변경하여 해결
- 리뷰 삭제 API에 대한 REST Docs 작성

[BE] 리뷰 삭제 기능 구현

---

frontend/src/constants/api.ts

[BugFix] github client ID를 배포용으로 변경

---

backend/src/docs/asciidoc/members.adoc
backend/src/main/java/com/woowacourse/f12/application/MemberService.java
backend/src/main/java/com/woowacourse/f12/exception/InvalidProfileArgumentException.java
backend/src/main/java/com/woowacourse/f12/presentation/MemberController.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/MemberDocumentation.java
backend/src/test/java/com/woowacourse/f12/presentation/MemberControllerTest.java

- 테스트 추가
- 회원정보 수정시 요청값이 유효하지 않은 테스트 케이스 추가
- 인수테스트에서 회원정보 수정한뒤 회원정보를 조회하여 검증하도록 수정
- 회원정보를 찾을 경우 추가정보가 없는 회원일 경우 예외 발생하도록 수정
- 회원정보 수정 요청에 대한 값 검증 추가

[BE] 회원 관련 기능 리팩토링

---

frontend/src/components/ReviewListSection/ReviewListSection.tsx
frontend/src/contexts/LoginContextProvider.tsx
frontend/src/custom.d.ts
frontend/src/mocks/data.ts
frontend/src/mocks/handlers.ts

- githubId -> gitHubId 네이밍 불일치 수정

[BugFix] 리뷰 카드에서 Github id가 보이지 않는 오류 수정

---

frontend/src/components/common/ProductSelect/ProductSelect.tsx

- 등록된 장비가 1개인 경우, 대표 장비 등록 선택을 하면 선택창이 삭제되는 현상
- useInventory의 otherProducts가 없을 경우 오류를 발생 시키던 때가 있어서 이를 방지하기 위해 배열의 길이가 0이면 컴포넌트를 렌더링 하지 않도록 설정
- 등록 장비 자체가 1개인 경우 선택하고 나면 otherProducts가 없기 때문에 문제 상황이 아닌데도 불구하고 컴포넌트가 렌더링 되지 않음
- 해당 조건부 렌더링 삭제, 코드가 수정돼서 더 이상 오류를 발생시키지 않음

[BugFix] 등록된 장비가 1개일 때 발생하던 오류를 수정

---

backend/src/main/java/com/woowacourse/f12/application/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/InventoryProductRepository.java
backend/src/test/java/com/woowacourse/f12/application/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/InventoryProductRepositoryTest.java

- 리뷰를 작성했을 때 장비가 인벤토리에 중복으로 추가되지 않도록 구현했다.
- 이미 존재하는 장비라면 예외를 던지는 것이아니라, 저장이 되지 않도록 했다.

[BE] 장비가 인벤토리에 중복 추가되는 버그가 발생한다

---

backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java

- 같은 회원이 같은 제품에 리뷰를 중복해서 작성하면 예외 발생 인수테스트 추가

[BE] 같은 회원이 같은 제품에 리뷰를 중복해서 작성하면 예외 발생 인수테스트 추가

---

backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProduct.java
backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepository.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/inventoryproduct/InventoryProductDocumentation.java
backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/product/KeyboardRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductControllerTest.java
backend/src/test/java/com/woowacourse/f12/support/InventoryProductFixtures.java

- InventoryProduct에 `@ManyToOne` 으로 Member를 직접 참조했다.
- Member에 `@OneToMany`로 InventoryProduct를 직접 참조했다.

[BE] 사용자와 인벤토리에 연관관계를 설정

---

frontend/src/components/common/CategoryNav/CategoryNav.tsx
frontend/src/constants/api.ts
frontend/src/hooks/api/useGetMany.tsx
frontend/src/hooks/useProducts.tsx
frontend/src/pages/Home/Home.tsx
frontend/src/pages/Products/Products.tsx

- products 페이지를 재사용, searchparams를 이용해서 카테고리를 분류
- category를 변경할 때 마다 refetch 하도록 설정
- useGetMany 훅의 params 전달 부분 코드 일부 수정

[FE] 카테고리 별 상품 목록 조회 페이지 구현 및 API 설정

---

frontend/src/pages/Products/Products.tsx

- 초기 렌더 시에는 state가 무조건 리뷰 많은 순으로 되어 있어서 발생한 오류
- useState에서도 hash에 따라 초기 상태를 변경하도록 처리

[BugFix] 인기 많은 상품 페이지에 존재하는 새로고침 오류 수정

---

backend/.gitignore

- 서브모듈로 분리한 h2 설정 파일을 git ignore

[BE] 서브모듈로 분리한 h2 설정 파일 ignore

---

frontend/src/components/common/CategoryNav/CategoryNav.tsx
frontend/src/pages/Products/Products.tsx

- 카테고리 타입을 일부 변경, 키를 카테고리 영어 value로 vaule를 한글 값으로 변경
- 페이지의 카테고리에 따라서 제목을 변경하도록 설정
- 하지만 인기/모든과 카테고리는 같이 호환은 아직 안 됨

feat: 카테고리 페이지에 따라 제목 변경 UI 구현

---

backend/build.gradle

- gradle 빌드의 `copyDocument` 태스크의 목표 경로를 `build` 디렉토리 아래로 옮겨서 `bootJar` 태스크 실행 시 RESTDocs 파일이 Jar에 포함되도록 설정

[Bugfix] jar 파일 생성 시 RESTDocs가 포함되지 않는 오류 수정

---

frontend/src/components/ProductListSection/ProductListSection.tsx
frontend/src/components/ReviewListSection/ReviewListSection.tsx
frontend/src/components/common/AsyncWrapper/AsyncWrapper.tsx
frontend/src/components/common/ErrorPlaceholder/ErrorPlaceholder.tsx
frontend/src/components/common/InfiniteScroll/InfiniteScroll.tsx
frontend/src/hooks/api/useAxios.tsx
frontend/src/hooks/api/useDelete.tsx
frontend/src/hooks/api/useGet.tsx
frontend/src/hooks/api/useGetMany.tsx
frontend/src/hooks/api/useGetOne.tsx
frontend/src/hooks/api/usePatch.tsx
frontend/src/hooks/api/usePost.tsx
frontend/src/hooks/api/usePut.tsx
frontend/src/hooks/useInventory.tsx
frontend/src/hooks/useProduct.tsx
frontend/src/hooks/useProducts.tsx
frontend/src/hooks/useReviews.tsx
frontend/src/pages/Home/Home.tsx
frontend/src/pages/Product/Product.tsx
frontend/src/pages/Products/Products.tsx
frontend/src/pages/Profile/Profile.tsx
frontend/src/utils/handleError.ts
frontend/src/utils/logError.ts

- API 요청의 Error 처리 통일
- get과 나머지로 나뉨
- get은 오류 상태를 화면에 표현해야 하므로 isError라는 상태를 로딩과 유사하게 활용
- 나머지는 액션에 대한 리액션이기 때문에 사용자에게 alert 해주는 방식
- UI적으로 사용자에게 표현하는 것 외에도 디버깅을 위해서 콘솔 창에 바로 현재의 상태를 표시해주도록 오류 메시지 설정
- Error 시 UI 구현

[FE] API 요청의 Error 처리 통일, Error UI 구현

---

frontend/src/components/ProfileCard/ProfileCard.style.tsx
frontend/src/components/ProfileCard/ProfileCard.tsx
frontend/src/components/ProfileSearchResult/ProfileSearchResult.style.tsx
frontend/src/components/ProfileSearchResult/ProfileSearchResult.tsx
frontend/src/components/SearchFilter/SearchFilter.style.tsx
frontend/src/components/SearchFilter/SearchFilter.tsx
frontend/src/components/common/ChipFilter/ChipFilter.style.tsx
frontend/src/components/common/ChipFilter/ChipFilter.tsx
frontend/src/components/common/HeaderNav/HeaderNav.tsx
frontend/src/components/common/SearchBar/SearchBar.style.tsx
frontend/src/components/common/SearchBar/SearchBar.tsx
frontend/src/constants/api.ts
frontend/src/constants/routes.ts
frontend/src/custom.d.ts
frontend/src/hooks/useProfileSearch.tsx
frontend/src/pages/ProfileSearch/ProfileSearch.style.tsx
frontend/src/pages/ProfileSearch/ProfileSearch.tsx
frontend/src/pages/Register/Register.tsx
frontend/src/pages/index.tsx

- 사용자 검색 기능 구현
- 경력, 직무, 쿼리에 따라 다른 검색결과를 출력

[FE] 사용자 검색 기능 구현

---

frontend/.eslintignore
frontend/package.json
frontend/src/constants/api.ts
frontend/src/custom.d.ts
frontend/webpack.common.js
frontend/webpack.dev.js
frontend/webpack.prod.js
frontend/webpack.test.js

- webpack 설정 분리
- `webpack.common.js`: 공통 설정
- `webpack.dev.js`: 개발 서버 설정
- `webpack.test.js`: 테스트 서버 설정
- `webpack.prod.js`: 실 서버 설정
- 스크립트 추가
- `npm run build-release`: 테스트 서버용 빌드 스크립트
- `npm run build-main`: 실 서버용 빌드 스크립트

[Hotfix, FE] 빌드 스크립트에 따라 API URL 주소를 다르게 빌드하게 설정

---

backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/dto/response/member/MemberWithProfileProductResponse.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/support/InventoryProductFixtures.java

- Member 객체에서 인벤토리 제품에서 대표 제품을 찾는 책임을 부여
- 도메인에서 대표 제품 찾는 메서드 호출

[BE] 회원을 검색할 때 대표장비가 아닌 다른 제품들도 나오는 오류 수정

---

backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java

- id 역순에 대한 정렬조건으로 제품을 조회할 때 데이터가 잘나오는지에 대한 테스트 추가

[BE] 페이지 조회 시 중복되는 아이템 조회되는 이슈 피드백 반영완료

---

backend/src/main/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolver.java
backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolverTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/review/ReviewControllerTest.java

[BugFix/BE] 페이지 조회 시 중복되는 아이템 조회되는 이슈 해결

---

.github/workflows/backend.yml

- `EnricoMi/publish-unit-test-result-action@v2`로 테스트 리포트 추가
- mikepenz/action-junit-report@v3로 PR에 테스트 실패에 대한 comment를 남기도록 설정

[BE] GitHub Actions workflow에 테스트 리포트 추가

---

frontend/src/components/ProductListSection/ProductListSection.tsx
frontend/src/components/ProfileCard/ProfileCard.tsx
frontend/src/components/ProfileSearchResult/ProfileSearchResult.tsx
frontend/src/components/ReviewListSection/ReviewListSection.tsx
frontend/src/components/common/NoDataPlaceholder/NoDataPlaceholder.tsx
frontend/src/components/common/ProductSelect/ProductSelect.tsx
frontend/src/hooks/api/useAxios.tsx
frontend/src/hooks/api/useGetMany.tsx
frontend/src/hooks/useInventory.tsx
frontend/src/mocks/data.ts
frontend/src/pages/Profile/Profile.tsx
frontend/src/pages/ProfileSearch/ProfileSearch.tsx
frontend/src/pages/Register/Register.tsx

[Bugfix/FE] 프론트엔드 버그 이슈 해결

---

backend/build.gradle
backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
backend/src/main/java/com/woowacourse/f12/presentation/LogInterceptor.java
backend/src/main/resources/application-local.yml
backend/src/main/resources/application-main.yml
backend/src/main/resources/application-release.yml
backend/src/main/resources/application.yml
backend/src/main/resources/log4j2/log4j2-local.xml
backend/src/main/resources/log4j2/log4j2-main.xml
backend/src/main/resources/log4j2/log4j2-release.xml
backend/src/test/resources/application.yml

- log4j2로 로깅 구현
- 프로파일 별 로깅 전략에 따라 로깅 구현
- 자세한 사항 노션 참고
- 인터셉터로 API 로깅 구현

[Feature/BE] 로깅 구현

---

backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java

- 회원 정보를 조회할 때 id에 대한 역순으로 정렬이 안되는 오류 수정
- 특정 메소드의 접근제어자 private으로 수정

[BE] 회원 정보를 조회할 때 id에 대한 역순으로 정렬이 안되는 오류 수정

---

backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java

- 회원정보 조회 시 기본 정렬 기준이 적용되도록 수정
- 특정 메소드에 대한 접근제어자 private으로 수정

[BugFix/BE] 회원 정보를 조회할 때 id에 대한 역순으로 정렬이 안되는 오류 수정

---

frontend/src/constants/api.ts
frontend/src/custom.d.ts
frontend/webpack.dev.js
frontend/webpack.prod.js
frontend/webpack.test.js

Github Client ID를 빌드 환경 별로 분기하도록 설정

[Chore/FE] 빌드 환경별로 소셜 로그인 링크 분기 설정

---

backend/.gitignore

- submodule gitignore 제거
- `security` 디렉토리 커밋

[Bugfix] 원격 레포지토리의 submodule 버전이 최신화되지 않는 오류 수정

---

frontend/src/components/common/UserInfo/UserInfo.tsx
frontend/src/hooks/useOtherInventory.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/OtherProfile/OtherProfile.tsx
frontend/src/pages/common/ClosedRoutes/ClosedRoutes.tsx
frontend/src/pages/common/RegisterIncompleteRoute/RegisterCompleteRoute.tsx
frontend/src/pages/index.tsx

- 로그인 하고 추가정보 입력하지 않은 경우 다른 경로로 이동하지 못하고 다시 추가정보 페이지로 돌아오게 변경
- 프로필 페이지에서도 추가정보 없는 경우 제외하고 표시하도록 오류 수정

[Hotfix/FE] 추가정보 입력하지 않은 사용자의 경로 이동 방지 추가

---

backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/domain/review/ReviewRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/presentation/member/CareerLevelConstant.java
backend/src/main/java/com/woowacourse/f12/presentation/member/JobTypeConstant.java
backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/review/ReviewControllerTest.java
backend/src/test/java/com/woowacourse/f12/support/MemberFixtures.java
frontend/package.json
frontend/src/components/common/UserInfo/UserInfo.tsx
frontend/src/hooks/api/usePatch.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/OtherProfile/OtherProfile.tsx
frontend/src/pages/Register/Register.tsx
frontend/src/pages/common/ClosedRoutes/ClosedRoutes.tsx
frontend/src/pages/common/RegisterIncompleteRoute/RegisterCompleteRoute.tsx
frontend/src/pages/index.tsx

- 추가 정보 저장 시 서버의 요청은 보내지만 그 새로운 상태를 프론트에서 저장하지 않아서 경로를 이동할 수 없었던 현상 수정

[Hotfix/FE] 추가 정보 저장 후 이동 경로 이동 불가한 오류 수정

---

frontend/src/hooks/api/usePatch.tsx
frontend/src/pages/Register/Register.tsx

- 추가 정보 저장 시 서버의 요청은 보내지만 그 새로운 상태를 프론트에서 저장하지 않아서 경로를 이동할 수 없었던 현상 수정

[Hotfix/FE] 추가 정보 저장 후 이동 경로 이동 불가한 오류 수정 

---

backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProduct.java
backend/src/main/java/com/woowacourse/f12/domain/review/Review.java

- `InventoryProduct`의 equals가 id 비교를 getter가 아닌 직접 참조로 비교하는 부분 수정
- `Review`의 equals가 JPA 프록시를 고려하지 않은 부분 수정

[BE] equals 메서드가 제대로 작성되지 않은 경우 수정

---

backend/src/main/java/com/woowacourse/f12/config/WebConfig.java
backend/src/test/java/com/woowacourse/f12/config/WebConfigTest.java

- 기존에는 CORS가 모든 origin에 대해 열려 있었으나, 실제 도메인 + 로컬 프론트엔드 환경에만 허용하도록 수정 완료

[BE] CORS가 허용된 origin 제한

---

frontend/src/components/Login/Login.tsx

깃헙에서 인증 취소 시에
1. 로그인 과정을 멈추고
2. 사용자에게 로그인을 취소했거나 오류가 발생했다는 메시지를 표시하고
3. 홈으로 이동

[Bugfix/FE] github oauth에서 인증을 취소할 시 발생하는 오류 해결

---

backend/src/main/java/com/woowacourse/f12/config/WebConfig.java
backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProduct.java
backend/src/main/java/com/woowacourse/f12/domain/review/Review.java
backend/src/test/java/com/woowacourse/f12/config/WebConfigTest.java

- 엔티티의 equals 메서드가 지연 로딩과 프록시를 고려하지 않은 경우 수정
- CORS를 특정 도메인에 대해서만 허용
- `https://f12.app`: 메인 서버
- `https://www.f12.app`: 메인 서버(www)
- `https://test.f12.app`: 테스트 서버
- `http://localhost:3000`: 로컬 프론트엔드 환경

[BugFix/BE] 프록시와 CORS 관련된 동작 이슈 수정

---

frontend/src/contexts/ModalContextProvider.tsx

- confirm 모달 취소 시 promise가 resolve 되도록 처리
- reject로 처리하려 했으나 confirm이 작동하는 방식은 false를 반환하는 것이므로 reject가 아니라 false가 resovle 되도록 구현

[FE] confirm 모달 창 promise가 무조건 resolve 되도록 수정

---

backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProduct.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/domain/review/Review.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberTest.java

- `@Builder` 어노테이션을 생성자에서 클래스로 이동
- `AllArgsContstructor`가 없는 `Product`는 제외
- 기본값이 필요한 필드에 `@Builder.Default` 사용

[BE] @Builder 사용 시 객체의 기본 값이 Builder에도 설정되도록 수정

---

backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProduct.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/domain/review/Review.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberTest.java

- #426 
- `@Builder` 어노테이션을 생성자에서 클래스로 이동
- `AllArgsContstructor`가 없는 `Product`는 제외
- 기본값이 필요한 필드에 `@Builder.Default` 사용

[BE] 빌더에 관련된 리팩토링

---

backend/src/main/java/com/woowacourse/f12/application/auth/AuthService.java
backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/dto/request/member/MemberRequest.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberTest.java
backend/src/test/java/com/woowacourse/f12/domain/product/ProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/support/MemberFixtures.java

- `Member` 도메인의 필드들을 update하는 로직을 하나로 통합

[BE] Member의 update 로직을 통합

---

backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepository.java
backend/src/test/java/com/woowacourse/f12/acceptance/AcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/documentation/member/MemberDocumentation.java
backend/src/test/java/com/woowacourse/f12/documentation/review/ReviewDocumentation.java
backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/product/ProductRepositoryTest.java

- 리뷰가 삭제되면 등록 장비도 삭제되도록 함
- 테스트 클래스에 접근수정자 default로 변경
- entityManager refresh 제거 및 clear 적용

[BE] 리뷰가 삭제되면 등록 장비도 삭제되는 로직 추가

---

backend/src/main/java/com/woowacourse/f12/config/LoggingConfig.java
backend/src/main/java/com/woowacourse/f12/exception/internalserver/IllegalRequestLogTimerStateException.java
backend/src/main/java/com/woowacourse/f12/presentation/LoggingInterceptor.java
backend/src/main/java/com/woowacourse/f12/support/RequestLogTimer.java
backend/src/test/java/com/woowacourse/f12/presentation/ControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolverTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthInterceptorTest.java
backend/src/test/java/com/woowacourse/f12/support/RequestLogTimerTest.java

- Clock 객체를 빈등록 하고 주입받는 방식으로 수정
- 테스트에서 Clock 객체를 모킹해서 테스트가 시간에 의존하지 않도록 수정
- 메서드 및 클래스 이름 수정

[BE] API 요청 소요시간 로깅 기능 피드백 반영

---

backend/src/main/java/com/woowacourse/f12/config/HibernateConfig.java
backend/src/main/java/com/woowacourse/f12/logging/ApiQueryCounter.java
backend/src/main/java/com/woowacourse/f12/logging/ApiQueryInspector.java
backend/src/main/java/com/woowacourse/f12/logging/LoggingInterceptor.java
backend/src/main/resources/log4j2/log4j2-local.xml
backend/src/main/resources/log4j2/log4j2-main.xml
backend/src/main/resources/log4j2/log4j2-release.xml
backend/src/test/java/com/woowacourse/f12/logging/ApiQueryCounterTest.java
backend/src/test/java/com/woowacourse/f12/logging/ApiQueryInspectorTest.java
backend/src/test/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolverTest.java
backend/src/test/java/com/woowacourse/f12/presentation/PresentationTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthInterceptorTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthPresentationTest.java
backend/src/test/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductPresentationTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberPresentationTest.java
backend/src/test/java/com/woowacourse/f12/presentation/product/ProductPresentationTest.java
backend/src/test/java/com/woowacourse/f12/presentation/review/ReviewPresentationTest.java

- 쿼리 개수를 저장할 QueryCounter 구현
- HTTP 요청의 쿼리 개수를 셀 ApiQueryInspector 구현
- 로그 관련된 패키지 분리

[Feature/BE] HTTP 요청마다 쿼리 개수를 세는 기능 구현

---

backend/src/main/java/com/woowacourse/f12/logging/LoggingFilter.java

- 로그에 QueryParam이 출력되지 않는 문제 해결완료
- 응답 content type 이 json 형식일 경우 body를 출력하지 않도록 구현완료
- 응답과 요청에 body가 없으면 출력하지 않도록 구현완료

[BugFix/BE] 로그에 QueryParam이 출력되지 않는 문제 해결

---

.github/workflows/backend.yml
backend/build.gradle

- 소나큐브 테스트 커버리지를 위한, 테스트가 필요없는 dto, fixtures등을 분석에서 제외함
- 리포트 결과에서 ❌ 표시가 나오는 항목에 대해서, 현재 진행하고 있는 실제 report 기준을 이용해서 표현할 수 있도록 변경

[BugFix] 소나큐브 테스트 커버리지 결과 수정 및 리포트 결과 정상화

---

backend/src/main/java/com/woowacourse/f12/logging/LoggingFilter.java

- 로그에 QueryParam이 출력되지 않는 문제 해결완료
- 응답 content type 이 json 형식일 경우 body를 출력하지 않도록 구현완료
- 응답과 요청에 body가 없으면 출력하지 않도록 구현완료

[BugFix/BE] 로그에 QueryParam이 출력되지 않는 문제 해결 (#498)

---

backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/dto/response/review/ReviewWithAuthorPageResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/review/ReviewWithAuthorResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthArgumentResolver.java
backend/src/main/java/com/woowacourse/f12/presentation/review/ReviewController.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/review/ReviewPresentationTest.java

- 특정 제품 리뷰 조회 시 컨트롤러에서 로그인한 사용자의 id 추가로 받도록 구현
- feat: 특정 제품 리뷰 조회 service 메서드에서 memberId 받도록 구현

[Feature/BE] 제품 리뷰 목록 조회 시 수정 및 삭제 가능 여부 기능 구현

---

frontend/src/components/Profile/ProfileCard/ProfileCard.tsx
frontend/src/components/Profile/UserInfo/UserInfo.style.tsx
frontend/src/components/Profile/UserInfo/UserInfo.tsx
frontend/src/constants/api.ts
frontend/src/hooks/api/usePost.tsx
frontend/src/hooks/useError.tsx
frontend/src/hooks/useFollowing.tsx
frontend/src/hooks/useInventory.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/Profile/Profile.tsx

- 다른 사용자의 프로필을 조회할 때 나 자신도 팔로우 버튼이 생겨있는 오류를 수정.
- 비로그인 사용자에게는 팔로우 버튼을 숨김
- 타회원 단일 프로필 조회 페이지에서, 비로그인 상태에서 타회원 프로필 조회 요청 시 Authorization 헤더를 포함하지 않도록 수정
-  프로필 페이지에도 팔로잉 기능 구현
- api endpoint 오타 수정

[Bugfix/FE] 팔로우 관련 오류를 수정

---

frontend/src/constants/cache.ts
frontend/src/contexts/CacheContextProvider.tsx
frontend/src/hooks/api/useCache.tsx
frontend/src/hooks/api/useGetMany.tsx
frontend/src/hooks/api/useGetOne.tsx
frontend/src/index.tsx

- API 캐싱 구현
- 캐싱 시간은 기본 5분, useGetOne, useGetMany에서 사용할 때는 3분으로 설정
- 외부 저장소에 저장하지 않고 앱 안에서만 저장 (API 요청에 대한 너무 긴 캐시 타임을 적용하지 않도록)
- 컨텍스트 기반으로 구현

[FE] API 요청에 대한 캐싱 구현

---

frontend/src/components/Profile/ProfileCard/ProfileCard.tsx
frontend/src/components/Profile/UserInfo/UserInfo.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.stories.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.tsx
frontend/src/constants/link.ts

- GitHub 프로필 이미지 사이즈가 크게 3가지로 분류되어 있음.
- 이미지 사이즈를 관리하는 객체를 만들고 3가지를 small, medium, large로 관리.

[Feature/FE] GitHub 프로필 이미지 크기를 최적화

---

backend/src/docs/asciidoc/auth.adoc
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthController.java
backend/src/test/java/com/woowacourse/f12/acceptance/AuthAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthControllerTest.java

- 리프레시 토큰을 가진 상태로 로그아웃 요청 시 쿠키 속 리프레시 토큰 max-age 를 0으로 해서 반환
- 리프레시 토큰이 없는 상태로 로그아웃 요청 시 예외 발생

[BE] 로그아웃 API 구현

---

backend/src/docs/asciidoc/auth.adoc
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthController.java
backend/src/test/java/com/woowacourse/f12/acceptance/AuthAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthControllerTest.java

#611 
- 리프레시 토큰을 가진 상태로 로그아웃 요청 시 쿠키 속 리프레시 토큰 max-age 를 0으로 해서 반환
- 리프레시 토큰이 없는 상태로 로그아웃 요청 시 예외 발생

[Feature/BE] 로그아웃 API 구현

---

frontend/src/constants/messages.ts
frontend/src/hooks/api/useAxios.tsx
frontend/src/mocks/handlers.ts

- errorCode를 백엔드는 문자열로 프론트엔드는 숫자로 받고 있어서 일치할 수 없는 문제 발생
- 프론트 쪽을 문자열로 수정

[Bugfix/FE] errorCode를 문자열로 수정

---

backend/src/main/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductService.java
backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProduct.java
backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepository.java
backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProducts.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java
backend/src/test/java/com/woowacourse/f12/support/fixture/MemberFixture.java

- InventoryProducts에 적용된 `@BatchSize`를 제거했다.
- InventoryProduct 내에서 Fetch EAGER 연관관계를 갖던 Product를 Fetch LAZY로 변경했다.
- 그 외, Product와 항상 같이 쓰이는 InventoryProduct 조회 쿼리에 대해서 Product와의 fetch join을 적용했다.

[BE/Feature] @BatchSize와 Fetch EAGER를 제거한다

---

backend/src/main/java/com/woowacourse/f12/config/WebConfig.java
backend/src/test/java/com/woowacourse/f12/config/WebConfigTest.java

- WebConfig CORS 설정에 exposeHeaders에 Set-Cookie 헤더 추가

[BugFix/BE] CORS exposeHeaders에 Set-Cookie 추가 (#631)

---

frontend/src/hooks/useInventory.tsx

- 현재는 내 리뷰 목록 조회 요청에 토큰을 사용하도록 설정이 되어있지 않음

[Bugfix/FE] inventory 훅에서 내 리뷰 목록 조회 시 토큰을 사용하도록 수정

---

frontend/src/components/Profile/ProfileCard/ProfileCard.style.tsx
frontend/src/components/Profile/ProfileCard/ProfileCard.tsx

- 프로필 카드의 링크를 a 태그에서 Link 컴포넌트로 변경

[FE] 프로필 카드의 링크를 a 태그에서 Link 컴포넌트로 변경

---

frontend/src/pages/index.tsx

- following 페이지에 대한 private 루트 설정 누락으로 비회원이 접근 가능한 것을 수정

[Bugfix/FE] following 페이지가 비회원이 접근할 수 없도록 설정

---

backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthController.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/RefreshTokenCookieProvider.java
backend/src/test/java/com/woowacourse/f12/presentation/PresentationTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/RefreshTokenCookieProviderTest.java

- RefreshTokenCookieProvider를 통해 리프레시 토큰 set cookie 할 때 Path, same site, max age 설정
- 리프레시 토큰 쿠키 제거 시에도 RefreshTokenProvider를 활용.

[BugFIx/BE] 리프레시 토큰 set cookie 헤더에 path, samesite, max age 설정

---

backend/src/main/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolver.java
backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthController.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/RefreshTokenCookieProvider.java
backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolverTest.java
backend/src/test/java/com/woowacourse/f12/presentation/PresentationTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/RefreshTokenCookieProviderTest.java
backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java

- CustomPageableArgumentResolver 에서 `/api/v1/products` 로 제품 페이징 조회 요청 시 정렬 기준에 `rating` 이 존재하면 세컨더리 정렬 기준으로 `reviewCount`를 추가하고, `reviewCount`가 존재하면 `rating`이 세컨더리 정렬 기준으로 추가되도록 구현.
- 추가된 기능에 맞게 테스트 수정

[BE] 제품 페이징 조회 세컨더리 정렬 기준 추가 기능

---

backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustom.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/dto/request/member/MemberRequest.java
backend/src/main/java/com/woowacourse/f12/dto/response/auth/LoginResponse.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/support/fixture/MemberFixture.java

- Member 조회에 대한 쿼리 성능을 개선
- 전체 유저 검색
- 키워드, 옵션이 없으면 커버링 인덱스 사용
- 키워드, 혹은 옵션이 1개라도 있으면 where 절 사용
- 옵션이 2개가 있다면 index를 타면서 매우 빠름
- 팔로잉 유저 검색
- 팔로잉 유저에 대해서 미리 쿼리를 날려서 index를 이용해서 자르고 시작
- 키워드, 옵션이 없으면 registered 사용해서 인덱스 탄다.
- 키워드, 옵션이 1개라도 있으면 where 사용
- 옵션이 2개가 있다면 index를 탄다.

[BE] Member 조회에 대한 쿼리 성능을 개선

---

backend/src/main/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolver.java
backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolverTest.java
backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java

- CustomPageableArgumentResolver 에서 `/api/v1/products` 로 제품 페이징 조회 요청 시 정렬 기준에 `rating` 이 존재하면 세컨더리 정렬 기준으로 `reviewCount`를 추가하고, `reviewCount`가 존재하면 `rating`이 세컨더리 정렬 기준으로 추가되도록 구현.
- 추가된 기능에 맞게 테스트 수정

[Feature/BE] 제품 페이징 조회 세컨더리 정렬 기준 추가 기능 (#649)

---

backend/src/main/java/com/woowacourse/f12/application/product/ProductService.java
backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/product/Product.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepositoryCustom.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/domain/review/Review.java
backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/product/ProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/product/ProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/product/ProductTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewTest.java

검색 키워드와 옵션이 모두 없는 경우
- 커버링 인덱스 활용
검색 키워드 혹은 옵션이 있는 경우
- 카테고리 옵션이 있다면 category 인덱스 활용
- 카테고리 옵션이 없다면 idx_rc_ar_id or idx_ar_rc_id 인덱스 활용

[BE] 프로덕트 검색 조회 쿼리를 개선한다

---

backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/product/Product.java
backend/src/main/java/com/woowacourse/f12/domain/review/Review.java
backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/product/ProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewTest.java

- 리뷰 생성, 수정, 삭제 시 리뷰 반영 메서드를 직접 호출하는 것으로 문제 해결

[BE] 리뷰 수정, 삭제 시 제품의 평점이 업데이트가 안되는 현상 수정

---

backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/product/Product.java
backend/src/main/java/com/woowacourse/f12/domain/review/Review.java
backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/product/ProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewTest.java

* fix: 리뷰 수정 및 삭제 시 제품에 적용 안되는 오류 수정
* test: 테스트 내용 수정
- 리뷰 생성, 수정, 삭제 시 리뷰 반영 메서드를 직접 호출하는 것으로 문제 해결

[BugFix/BE] 리뷰 수정, 삭제 시 제품의 평점이 업데이트가 안되는 현상 수정 (#662)

---

backend/src/main/java/com/woowacourse/f12/domain/review/ReviewRepository.java
backend/src/main/java/com/woowacourse/f12/domain/review/ReviewRepositoryCustom.java
backend/src/main/java/com/woowacourse/f12/domain/review/ReviewRepositoryCustomImpl.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewRepositoryTest.java

- QueryDSL 구현체에서 커버링 인덱스 데이터를 가져오는 쿼리를 실행하고 멤버와 제품 테이블과 페치조인한 쿼리를 실행하도록 구현

[BE] 리뷰 조회 시 커버링 인덱스를 사용한다.

---

backend/src/main/java/com/woowacourse/f12/domain/review/ReviewRepository.java
backend/src/main/java/com/woowacourse/f12/domain/review/ReviewRepositoryCustom.java
backend/src/main/java/com/woowacourse/f12/domain/review/ReviewRepositoryCustomImpl.java
backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewRepositoryTest.java

- QueryDSL 구현체에서 커버링 인덱스 데이터를 가져오는 쿼리를 실행하고 멤버와 제품 테이블과 페치조인한 쿼리를 실행하도록 구현

[Feature/BE] 리뷰 조회 시 커버링 인덱스를 사용한다

---

backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberTest.java

- 팔로우 수 증가, 감소에 대한 로직 Member update 로직과 분리
- 재로그인 시 팔로우 수가 변하지 않음에 대한 인수테스트 추가

[Hotfix/BE] 로그아웃 시 팔로워 수가 초기화 되는 현상을 수정한다

---

backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java

- 검색 조건 없이 나의 following 목록 조회 시 following_id 목록 조회하는 부분 join절 없앨 것
- 사용자 검색 시 결과 값이 없는 경우 (로그인 여부 상관 X, 팔로잉 검색, 기본 검색 상관 모두) 
- 해당 회원의 inventoryProduct를 조회하지 않을 것
- 팔로잉 여부를 확인하는 쿼리를 보내지 않을 것

[BE] 스프린트5에 대한 버퍼를 진행한다

---

frontend/src/components/Profile/ProfileCard/ProfileCard.style.tsx
frontend/src/components/Profile/ProfileCard/ProfileCard.tsx

- 깃허브 프로필 링크와 서비스 내 사용자 프로필 페이지 이동 링크가 공유되고 있어서 발생
- 깃허브 프로필 링크용 스타일드 컴포넌트는 별개로 다시 만들어서 문제 해결

[Hotfix/FE] 깃허브 프로필 링크 오류 수정

---

backend/src/main/resources/application.yml
backend/src/main/resources/log4j2/log4j2-local.xml
backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/FollowingRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/product/ProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewRepositoryTest.java

local 환경에서 respository test 시 쿼리 로그가 2번 남는 현상 수정
1. 처음에는 JPA의 로그를 활용하지 않고, log4j2의 로그를 활용하도록 수정하려고 했으나, format_sql이 지켜지지 않고 한줄로 나옴.
-> 실패
2. format_sql = true & show_sql=false로 설정하더라도 해당 현상이 해결되지 않음. (show-sql 설정이 무시되는 것 같음)
-> 실패
3. local 환경에서는 log4j2의 sql 로그를 활용하지 않고, JPA의 로그를 활용하려고 했음. Repository Test에서 쿼리 로그가 2번 남는 현상은 고쳐졌지만, release, main 환경에서 log4j2의 로그는 파일에 남겨지고 있지만, JPA의 로그는 스프링 부트 로그에 남고 있을 것이라 판단(nohup.output 에 기록되고 있을 것이다.)
-> 완벽하지 않은 성공
따라서 log4j2의 로그를 활용하기로 하고, JPA의 로그 남기는 옵션을 끄기로 했음.
방법은 문제가 되는 `@DataJpaTest` 어노테이션을 사용하는 테스트에서 show-sql을 false로 설정

[BE] local 환경에서 repository test 시 쿼리 로그가 2번 남는 현상 수정

---

backend/src/main/java/com/woowacourse/f12/application/auth/JwtProvider.java
backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthInterceptor.java
backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
backend/src/test/java/com/woowacourse/f12/application/auth/JwtProviderTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthInterceptorTest.java
backend/src/test/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/review/ReviewControllerTest.java
frontend/src/components/Profile/ProfileCard/ProfileCard.style.tsx
frontend/src/components/Profile/ProfileCard/ProfileCard.tsx

- JWT의 subject에는 "AccessToken" 이라는 값을 넣어 토큰의 주제를 표시
- subject 대신 claim에 payload를 저장
- payload를 꺼낼 때 subject가 "AccessToken" 인지 검증
- payload를 claims에서 꺼냄

[BE] JWT 생성 방식 변경

---

backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
backend/src/test/java/com/woowacourse/f12/acceptance/support/DatabaseCleanup.java
backend/src/test/java/com/woowacourse/f12/acceptance/support/EscapeSqlUtil.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java

인수테스트를 위한 Table을 truncate하는 로직에서 SQL을 생성하는 방식을 변경했다.

[Bugfix/BE] DatabaseCleanup SQL 생성 방식 변경

---

backend/build.gradle
backend/src/docs/asciidoc/auth.adoc
backend/src/main/java/com/woowacourse/f12/application/auth/GitHubOauthClient.java
backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepositoryCustomImpl.java
backend/src/main/java/com/woowacourse/f12/exception/internalserver/OauthProcessingException.java
backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
backend/src/test/java/com/woowacourse/f12/application/auth/AuthServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/GitHubOauthClientTest.java
backend/src/test/java/com/woowacourse/f12/application/member/MemberServiceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java
backend/src/test/java/com/woowacourse/f12/support/FakeGitHubApiController.java

- WebClient를 HttpClient로 변경
- webFlux 의존성 제거

[Feature/BE] WebClient를 HttpClient로 변경

---

backend/src/main/java/com/woowacourse/f12/application/auth/GitHubOauthClient.java

- GithubOauthClient 에서 HttpClient 요청 시 Accept: application/json을 추가한다.

[BugFix/BE] Github Oauth 요청 시 Accept 헤더를 추가한다.

---

backend/src/main/java/com/woowacourse/f12/application/auth/GitHubOauthClient.java
backend/src/main/java/com/woowacourse/f12/dto/response/auth/GitHubProfileResponse.java
backend/src/main/java/com/woowacourse/f12/dto/response/auth/GitHubTokenResponse.java
backend/src/main/java/com/woowacourse/f12/exception/internalserver/OauthJsonParsingException.java

- `@JsonIgnoreProperties(ignoreUnknown = true)`를 응답 DTO에 추가
- JSON 파싱 당시에 생긴 예외를 따로 분리해주기 위해서 커스텀 예외 추가 (하지만 내부 서버 예외 이므로 에러코드를 추가하지 않음)

[BugFix/BE] Github Oauth의 응답값이 DTO 필드에 존재하지 않는 경우 매핑 될 수 있도록 수정

---

backend/src/main/java/com/woowacourse/f12/application/auth/AuthService.java
backend/src/main/java/com/woowacourse/f12/application/auth/JwtProvider.java
backend/src/main/java/com/woowacourse/f12/application/auth/token/InmemoryRefreshTokenRepository.java
backend/src/main/java/com/woowacourse/f12/application/auth/token/JwtProvider.java
backend/src/main/java/com/woowacourse/f12/application/auth/token/MemberPayload.java
backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshToken.java
backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenProvider.java
backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepository.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/domain/member/Role.java
backend/src/main/java/com/woowacourse/f12/dto/response/auth/IssuedTokensResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthArgumentResolver.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthInterceptor.java
backend/src/main/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductController.java
backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
backend/src/main/java/com/woowacourse/f12/presentation/review/ReviewController.java
backend/src/main/java/com/woowacourse/f12/support/MemberPayloadSupport.java
backend/src/test/java/com/woowacourse/f12/application/auth/AuthServiceTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/JwtProviderTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/token/FakeJwtProvider.java
backend/src/test/java/com/woowacourse/f12/application/auth/token/InmemoryRefreshTokenRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/token/JwtProviderTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenProviderTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenTest.java
backend/src/test/java/com/woowacourse/f12/presentation/PresentationTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthInterceptorTest.java
backend/src/test/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/review/ReviewControllerTest.java

- JWT의 subject에는 "AccessToken" 이라는 값을 넣어 토큰의 주제를 표시
- subject 대신 claim에 payload를 저장
- payload를 꺼낼 때 subject가 "AccessToken" 인지 검증
- payload를 claims에서 꺼냄
- Member에 Role 필드 추가
- @VerifiedMember의 대상 타입 Long -> MemberPayload 변경
- MemberPayload는 id와 Role을 가지고 있음
- JWT가 Payload 객체로 변환할 때 자동으로 타입 변환해줌
- 기존처럼 NumberFormatException을 잡는 것이 아니라 RequiredTypeException을 잡아서 TokenInvalidFormatException으로 바꿔줌

[Feature/be] 인증 인가 수정

---

backend/src/main/java/com/woowacourse/f12/dto/request/product/ProductCreateRequest.java
backend/src/main/java/com/woowacourse/f12/dto/request/product/ProductUpdateRequest.java
backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/product/ProductServiceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthInterceptorTest.java
backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java

- 제품 수정 요청 및 제품 삭제 요청 DTO에 사용되는 Category enum을 CategoryConstant enum으로 교체.

[BugFix/BE] 제품 수정, 삭제 API DTO 카테고리 enum을 DTO용 Constant로 수정

---

backend/src/docs/asciidoc/auth.adoc
backend/src/main/java/com/woowacourse/f12/application/auth/AuthService.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/dto/response/auth/AdminLoginResponse.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthController.java
backend/src/test/java/com/woowacourse/f12/application/auth/AuthServiceTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthControllerTest.java

[Feature/BE] 어드민 로그인 api 구현

---

backend/src/main/java/com/woowacourse/f12/application/auth/AuthService.java
backend/src/main/java/com/woowacourse/f12/application/auth/GitHubOauthClient.java
backend/src/main/java/com/woowacourse/f12/config/OauthClientConfig.java
backend/src/test/java/com/woowacourse/f12/application/auth/GitHubOauthClientTest.java
backend/src/test/resources/application.yml

- GitHubOauthClient를 두 개로 분리
- 프로덕션 인증을 처리하고 redirect하는 빈과 어드민 인증을 처리하고 redirect하는 빈을 분리
- 각각의 빈은 `@Qualifier`를 통해 구분

[Feature/BE] 프로덕션 인증 기능과 어드민 인증 기능 분리

---

backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/application/product/ProductService.java
backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/logging/ApiQueryInspector.java
backend/src/main/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolver.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthArgumentResolver.java
backend/src/main/java/com/woowacourse/f12/support/AuthTokenExtractor.java
backend/src/main/java/com/woowacourse/f12/support/RepositorySupport.java
backend/src/test/java/com/woowacourse/f12/support/FakeGitHubApiController.java

Objects 의 null 체크 메서드를 제거한다.
Objects 의 null 체크 메서드는 람다식에서 메서드 참조를 위해 만들어졌다. 일반적인 경우에는 ==, !=null 을 사용하도록 한다.

[Feature/BE] Objects 의 null 체크 메서드를 제거

---

frontend/src/components/DeskSetup/DeskSetup.style.tsx
frontend/src/components/DeskSetup/DeskSetup.tsx
frontend/src/components/Profile/InventoryProductList/InventoryProductList.style.tsx
frontend/src/components/Profile/ProfileCard/ProfileCard.style.tsx
frontend/src/components/Profile/ProfileCard/ProfileCard.tsx
frontend/src/components/Profile/ProfileSearchResult/ProfileSearchResult.style.tsx
frontend/src/components/Profile/UserInfo/UserInfo.style.tsx
frontend/src/components/common/Modal/Modal.style.tsx
frontend/src/components/common/SearchBar/SearchBar.style.tsx
frontend/src/mocks/data.ts
frontend/src/pages/Profile/Profile.style.tsx
frontend/src/pages/ProfileSearch/ProfileSearch.style.tsx
frontend/src/pages/common/PageLayout/PageLayout.style.tsx

- 프로필 페이지 반응형 적용
- 팔로잉 검색(프로필 검색) 페이지 반응형 적용
+) 구현하기로 했었던 플로팅 버튼은 작은 화면에서 리뷰 카드나 상품 카드 요소를 가리는 문제가 있어 오히려 사용성이 저하될 수도 있겠다는 생각이 들었습니다. 모바일에서는 메뉴바들이 하단으로 내려가 있고, 원하는 메뉴에 쉽게 진입할 수 있으므로 플로팅 버튼을 통해 상단으로 이동하는 경우도 적지 않을까 하는 생각도 들었습니다.
일부 요소를 가리더라도 플로팅 버튼을 통해 위로 올라갈 수 있게 vs 플로팅 버튼을 구현하지 않고 요소를 가리지 않게 
간단한 부분이라 구현은 금방할 수 있겠지만 사용성 측면에서 프론트엔드 + 백엔드와 함께 추가적인 논의가 필요할 것 같아요!

[FE] 프로필 페이지, 팔로잉, 프로필 검색 반응형 디자인을 적용

---

backend/src/main/java/com/woowacourse/f12/application/member/MemberService.java
backend/src/main/java/com/woowacourse/f12/application/product/ProductService.java
backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
backend/src/main/java/com/woowacourse/f12/logging/ApiQueryInspector.java
backend/src/main/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolver.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthArgumentResolver.java
backend/src/main/java/com/woowacourse/f12/support/AuthTokenExtractor.java
backend/src/main/java/com/woowacourse/f12/support/RepositorySupport.java
backend/src/test/java/com/woowacourse/f12/support/FakeGitHubApiController.java

Objects 의 null 체크 메서드를 제거한다.
Objects 의 null 체크 메서드는 람다식에서 메서드 참조를 위해 만들어졌다. 일반적인 경우에는 ==, !=null 을 사용하도록 한다.

[Feature/BE] Objects 의 null 체크 메서드를 제거 

---

backend/src/main/java/com/woowacourse/f12/application/auth/AuthService.java

- 액세스 토큰 발급 로직 메서드에 `@Transaction`메서드를 추가한다.

[BugFix/BE] 액세스 토큰 발급 시 read only 커넥션 500 에러 수정

---

frontend/src/components/Product/ProductListSection/ProductListSection.tsx

제품 카드를 클릭했을 때 새로운 탭에서 링크가 열리도록 설정해서 목록의 스크롤이 유지될 수 있는 효과를 만든다.

[FE] 제품 카드를 클릭했을 때 새로운 탭에서 링크가 열리도록 설정

---

frontend/src/components/Product/ProductDetail/ProductDetail.style.tsx
frontend/src/components/Product/ProductDetail/ProductDetail.tsx
frontend/src/constants/api.ts

제품의 정보를 직접 저장하는 대신 다나와/구글로 검색할 수 있는 외부 링크 제공

[FE] 제품 검색용 링크 추가

---

backend/build.gradle
backend/src/main/resources/application.yml
backend/src/main/resources/db/migration/V1__init.sql
backend/src/test/java/com/woowacourse/f12/acceptance/AcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
backend/src/test/java/com/woowacourse/f12/domain/RepositoryTest.java
backend/src/test/resources/application.yml

- flyway로 DB 형상관리 툴을 적용한다
- 기존에 있는 데이터베이스를 활용해서 init.sql을 작성했다.
- Test 코드를 ddl-auto: create를 이용하는 것이 아니라, resource에 있는 init.sql을 활용하여 실제 db와 Spring boot test 환경 db의 싱크를 맞추었다.

[BE] DB 형상관리 툴을 적용한다

---

backend/build.gradle
backend/src/main/resources/application.yml
backend/src/main/resources/db/migration/V1__init.sql
backend/src/test/java/com/woowacourse/f12/acceptance/AcceptanceTest.java
backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
backend/src/test/java/com/woowacourse/f12/domain/RepositoryTest.java
backend/src/test/resources/application.yml

- flyway로 DB 형상관리 툴을 적용한다
- 기존에 있는 데이터베이스를 활용해서 init.sql을 작성했다.
- Test 코드를 ddl-auto: create를 이용하는 것이 아니라, resource에 있는 init.sql을 활용하여 실제 db와 Spring boot test 환경 db의 싱크를 맞추었다.

[Feature/BE] DB 형상관리 툴 Flyway를 도입

---

backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepository.java
backend/src/main/java/com/woowacourse/f12/domain/review/Review.java
backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
backend/src/test/java/com/woowacourse/f12/domain/product/ProductRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewRepositoryTest.java
backend/src/test/java/com/woowacourse/f12/domain/review/ReviewTest.java

- 제품 통계 정보(리뷰 개수, 리뷰 총 점수, 리뷰 평균 점수)가 리뷰 작성, 수정, 삭제의 동시성 문제로 제대로 업데이트 되지 않는 문제가 발생
- 더티 체킹을 유지한 상태로 문제를 해결하려면 명시적으로 락을 걸어야 하지만 애플리케이션 단의 락은 위험
- 애플리케이션 단의 명시적 락이 아닌, 데이터베이스의 암시적 락을 활용하기 위해 JPQL을 직접 사용하도록 변경
- 리뷰 작성, 수정, 삭제 각각에 대해 통계를 반영하는 JPQL 작성
- 기존에 이미 테이블에 있는 정보를 사용하여 업데이트 하도록 작성
- 최대한 DBMS에 종속적이지 않도록 작성
- JPQL로 작성하고, DBMS마다 다른 계산 방식을 해결하기 위해 나눗셈시 미리 double로 타입 캐스팅
- JpaRepository의 명시적 flush 기능 사용
- `@Modifying(clearAutomatically = true)` 옵션을 사용하기 때문에 영속성 컨텍스트가 초기화 됨
- 이 때 JPQL은 product 테이블에 대해서만 나가므로, review나 inventoryProduct에 대한 수정, 삭제 쿼리는 flush되지 않음
- clearAutomatically = true에 의해 영속성 컨텍스트가 초기화되어 쿼리가 실행되지 않음
- JpaRepository의 flush를 직접 호출하여 영속성 컨텍스트 초기화 이전에 모든 쓰기 지연 저장소의 쿼리가 flush 되도록 지정

[BE] 리뷰 작성 시 제품 통계 정보의 정합성을 맞추도록 수정

---

backend/src/main/java/com/woowacourse/f12/application/batch/BatchService.java
backend/src/main/java/com/woowacourse/f12/application/batch/FollowerCountBatchScheduler.java
backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
backend/src/main/java/com/woowacourse/f12/config/SchedulerConfig.java
backend/src/main/java/com/woowacourse/f12/domain/member/MemberRepository.java
backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepository.java
backend/src/test/java/com/woowacourse/f12/domain/member/MemberRepositoryTest.java

- 사용자는 구체적으로 누가 팔로우 하고 있는지 확인하지 않고, 팔로워 수만 확인하도록 구현되어 있으므로, 팔로우 버튼을 눌렀을 때 팔로잉 수가 올라가거나 언팔로우 버튼을 눌렀을 때 팔로워 수가 내려가기만 하면 됨.
- 기존 더티 체킹 방식의 문제는 트랜잭션 시작부터 커밋 사이에 커밋된 다른 트랜잭션의 업데이트 정보가 유실된다는 점이 문제지, 최소한 본인이 누른 팔로우 / 언팔로우에 대해서는 적용이 되고 있음
- 따라서 매 번 정합성을 맞출 필요는 없음
- 스프링부트의 스케줄러를 사용해서 배치 업데이트 쿼리를 매 시간마다 실행

[BE] 데이터 정합성을 맞추는 스케줄러 작성

---

frontend/cypress/e2e/spec.cy.ts
frontend/src/components/Product/ProductDetail/ProductDetail.style.tsx
frontend/src/components/Product/ProductDetail/ProductDetail.tsx
frontend/src/components/Product/ProductListSection/ProductListSection.tsx
frontend/src/constants/api.ts

피드백을 반영해서 스크롤 유지, 제품 상세 정보 문제를 해결한다.
- 스크롤 유지: 실제로 스크롤을 유지하는 대신 제품을 새 창에서 열어주는 것으로 해결한다.
- 제품 상세 정보: 실제로 정보를 추가하는 것은 어려우므로 다나와, 구글로 연결하는 링크를 만들어서 외부로 연결한다.

[Feature/FE] 사용자 피드백을 반영해서 스크롤 유지, 제품 상세정보 우회 구현

---

frontend/src/components/common/BottomSheet/BottomSheet.style.tsx

[fix: BottomSheet container z-index 조정](https://github.com/woowacourse-teams/2022-f12/commit/d4aa5ee66e56b373e1c63783537b546fc1ae0b99)

[FE] 바텀 시트가 리뷰 작성 버튼에 가려지는 문제 수정

---

frontend/src/components/Profile/UserInfo/UserInfo.tsx
frontend/src/components/Review/ReviewCard/ReviewCard.tsx
frontend/src/pages/Profile/Profile.style.tsx
frontend/src/pages/Profile/Profile.tsx

깃헙 최대 유저네임 길이에 대응하도록 스타일 수정
- 리뷰 카드에서 이름과 평점 줄바꿈
- 프로필 페이지의 사용자 정보 레이아웃 수정

[Bugfix/FE] 깃헙 최대 유저네임 길이에 대응하도록 스타일 수정

---

frontend/src/components/Review/ReviewCard/ReviewCard.style.tsx
frontend/src/mocks/data.ts

- 과도한 공백문자 댓글 모킹 추가
- 댓글 p 태그에 word-break: break-all 속성 부여

[BugFix/FE] 공백문자를 과도하게 입력할 경우 레이아웃이 깨지는 문제 수정

---

backend/src/main/java/com/woowacourse/f12/config/WebConfig.java
backend/src/test/java/com/woowacourse/f12/config/WebConfigTest.java

- 어드민 페이지(https://admin.f12.app)에 대해 CORS가 허용되지 않아 어드민 페이지가 작동하지 않는 문제를 해결

[HotFix] 어드민 페이지에 대해 CORS를 허용

---

frontend/src/components/common/LazyImage/LazyImage.style.tsx
frontend/src/mocks/data.ts

높이가 긴 이미지가 잘리는 오류를 해결한다
- 이미지의 object-fit을 contain으로 수정
- 이미지에 높이 100% 설정

[Hotfix/FE] 높이가 긴 이미지가 잘리는 오류 수정

---

frontend/babel.config.json
frontend/package-lock.json
frontend/package.json
frontend/src/index.tsx

##문제 상황
홈화면에서 캐싱에 사용한 배열 내장 메서드인 `at`이 오래된 브라우저에서 지원이 되지 않아서 발생하는 오류
- babel 설정 상으로 0.5% 이상의 점유율을 가진 브라우저에 지원하도록 설정해두었음 => 하지만 제대로 적용되지 않음
```json
"targets": "> 0.5%, not dead"
```
- 검색 결과 필요한 함수를 적절히 polyfill 하려면 core-js를 설치하고 설정해야함
- https://babeljs.io/docs/en/babel-preset-env#usebuiltins
- core-js를 설치하고 babel.confing.json에 설정 추가
- index.tsx에 core-js의 stable 버전을 import

[Bugfix/FE] babel/core-js 설치 및 설정을 통해 at 매서드 오류 해결

---

frontend/src/components/common/InfiniteScroll/InfiniteScroll.tsx
frontend/src/index.tsx

무한스크롤 오류 수정
- 첫 화면에서 두 페이지 (초기 + 그 다음)을 불러오면 발생
- intersection observer는 isIntersecting이 false에서 true로 변경될 때 콜백함수가 실행
- 위 엣지 케이스에서는 계속 화면에 intersecting이어서 그 다음 페이지를 불러오지 않음
- useEffect 훅을 사용해 children이 변경될 때 cleanup 콜백함수로 unobserve 한 뒤 다시 observe하도록 해서 화면에 존재하는 동안에는 새로운 데이터를 불러운 뒤 계속 콜백함수가 호출되도록 수정
```ts
useEffect(() => {
if (!endRef.current) return;
endOfContentObserver.observe(endRef.current);
return () => {
if (!endRef.current) return;
endOfContentObserver.unobserve(endRef.current);
};
}, [children]);
```

[Bugfix/FE] intersection observer 오류 수정

---

frontend/package.json

jenkins에서 프론트엔드 빌드 실패
jenkins에서 build할 때 devDependency는 설치하지 않는 --production 옵션을 사용 중이기 때문에
devDependency에 위 두 플러그인이 있으면 설치되지 않아 성공적으로 build 할 수 없는 오류 발생

[Bugfix/FE] ts-loader, fork-ts-checker 플러그인을 devDeps => deps로 변경

---

frontend/src/constants/cache.ts
frontend/src/contexts/CacheContextProvider.tsx

- MINS 변수 오타 수정 (100ms -> 1000ms)
- 캐시 시간 1분으로 감소
- 현재 캐시 시간이 5분으로 설정되어 있는데 해당 시간 내에 데이터가 변경되는 경우, 사용자가 이전 데이터를 계속해서 보는 문제가 발생합니다. 서버로부터 캐싱을 하는 것이 가장 좋겠지만, 백엔드 크루들의 시간적 여력이 부족하고, 이미지도 자체적으로 관리하고 있는 상황이 아니기 때문에 현 상황에서는 클라이언트 측에서 캐싱 타임을 줄이는게 가장 현실적인 방안인 것 같습니다. 현재 서비스 규모에서 데이터가 1분 미만의 단위로 변경될 가능성은 크지 않다고 판단하여 1분으로 수정하였습니다.

[FE] API 캐시 타임 수정

---

frontend/tsconfig.json

- removeComments는 기본값이 false인데 tsconfig에 명시되어 있어 제거했습니다.
- https://www.typescriptlang.org/tsconfig#removeComments
- `Strips all comments from TypeScript files when converting into JavaScript. Defaults to false.`

[FE] 불필요한 tsconfig 설정 제거

---

backend/src/test/java/com/woowacourse/f12/presentation/CustomPageableArgumentResolverTest.java
backend/src/test/java/com/woowacourse/f12/presentation/PresentationTest.java
backend/src/test/java/com/woowacourse/f12/presentation/UrlLengthCheckInterceptorTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthInterceptorTest.java
backend/src/test/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/member/MemberControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java
backend/src/test/java/com/woowacourse/f12/presentation/review/ReviewControllerTest.java

각 Presentation 테스트에서 주입하는 `@MockBean` 의 구성이 매 테스트 클래스마다 달라지기 때문에 새롭게 application context를 새로 띄우는 현상이 발견되었다. 이를 개선하기 위해서 기존에 존재했던 Presentation 클래스를 활욤해서 Test에서 활용되는 각각의 `@MockBean`을 모두 구성한 후 application Context를 재활용해서 사용할 수 있도록 개선했다.
**Application Context Load 횟수**
기존 12번 -> 개선 후  6번
**테스트 속도**
속도상으로 Intelij 에서 속도는 Application Context를 로딩하는 시간이 포함되어 나오지 않기 때문에 큰 변화는 없지만, 실제로 TEST를 실행하고 시간을 쟀을 때 유의미한 시간 차이가 있다.
(Mac Pro 2019 기준으로)
기존 평균적으로 41-42초 소요 -> 개선 후 평균적으로 36-37초로 개선

[Refactor/BE] PresentationTest application context 통합으로 테스트 실행 속도 개선

---

backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthController.java
backend/src/main/java/com/woowacourse/f12/presentation/auth/RefreshTokenCookieProvider.java
backend/src/main/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductController.java
backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
backend/src/main/java/com/woowacourse/f12/presentation/product/ProductController.java
backend/src/main/java/com/woowacourse/f12/presentation/review/ReviewController.java
backend/src/test/java/com/woowacourse/f12/presentation/auth/RefreshTokenCookieProviderTest.java

- 200 OK를 내려주는 응답에 대해서 스프링은 ResponseEntity<T>의 형태가 아니라 T의 반환값으로도 처리할 수 있음.
- 특별히 처리를 해주어야 하는 메서드가 없었기 때문에 모든 200 OK 응답들은 ResponseBody로 사용할 DTO를 그대로 리턴값으로 사용하도록 수정
- Cookie 값을 내려주는 컨트롤러 메서드에서 왜 굳이 HttpResponse를 파라미터로 받아서 처리했을까?
```java
return ResponseEntity.ok().header()...
```
으로도 처리할 수 있지 않았을까?

[Refactor/BE] 불필요한 ResponseEntity 제거
